### ISSUE TITLE
How to use the PX4 avoidance with AirSim?

### ISSUE THREAD

**Issue by HoaPham2711** [PX4/avoidance#114]
I want to use the PX4 avoidance with AirSim (https://github.com/Microsoft/AirSim) instead of the Gazebo. But I can't find any document to setup it with AirSim, Can anyone give me an advice?

**Comment by HoaPham2711** [comment]
I'm using the airsim_ros_wrapper (https://github.com/Mayankm96/airsim_ros_wrapper) to publish tf, odom, sensor data to ROS

**Comment by nicovanduijn** [comment]
Did you manage to get a regular PX4 SITL simulation running without the OA? I've tried this myself a while back and failed, I'd be interested to see how it can be done

**Comment by HoaPham2711** [comment]
> Did you manage to get a regular PX4 SITL simulation running without the OA?
I don't really understand, can you explain me?

**Comment by nicovanduijn** [comment]
Ignoring the avoidance, were you able to run PX4 and connect it to AirSim?

**Comment by HoaPham2711** [comment]
Yes, I was able to run PX4  and connect it to Airsim

**Comment by ming94good** [comment]
Hi, were you able to do so?

**Comment by awaisali88** [comment]
How did you manage to get it done. Can you explain which topics are needed for the local_planner from airsim.

**Comment by chungggg** [comment]
@ming94good @awaisali88 I tested with master branch on AirSim v1.5.0-linux, PX4 Autopilot v1.11.3, Unreal Engine 4.25, Ubuntu 20.04 and working perfectly.
1. Remove start gazebo node
2. Change pointcloud topic with pointcloud topic name from airsim
3. Start avoidance local planner node, start airsim, start airsim ros node
Maybe you need transform ned_world frame with fcu frame

**Comment by Yueting-Li** [comment]
> @ming94good @awaisali88 I tested with master branch on AirSim v1.5.0-linux, PX4 Autopilot v1.11.3, Unreal Engine 4.25, Ubuntu 20.04 and working perfectly.
> 
> 1. Remove start gazebo node
> 2. Change pointcloud topic with pointcloud topic name from airsim
> 3. Start avoidance local planner node, start airsim, start airsim ros node
>    Note: Maybe you need transform ned_world frame with fcu frame

Hi,
    I am trying to use the PX4 avoidance with AirSim and just followed the steps you said, but something went wrong. I could see the obstacle point cloud in front of the plane, then I moved 2D Nav Goal in rviz. But the plane could not avoid obstacle and just shaked. Can you give me some advice? I will appreciate it if you can upload the modified PX4-avoidance.
   Thank you very much!

**Comment by hwadiadinkra** [comment]
Remove start gazebo node
Change pointcloud topic with pointcloud topic name from airsim
Start avoidance local planner node, start airsim, start airsim ros node
Note: Maybe you need transform ned_world frame with fcu frame

Do you mean static transform, or a transform publisher? Can you show your TF tree?

**Comment by Thanmai01** [comment]
> Remove start gazebo node Change pointcloud topic with pointcloud topic name from airsim Start avoidance local planner node, start airsim, start airsim ros node Note: Maybe you need transform ned_world frame with fcu frame
> 
> Do you mean static transform, or a transform publisher? Can you show your TF tree?

How exactly we remove gazebo node?
In which files we need to edit that?
DId you run local_planner in airsim?

**Comment by Dvirus20** [comment]
@chungvmo Can you please provide more clarification on the steps:
1.  how and from where do we need to remove gazebo node.
2.  How to change pointcloud topic with pointcloud topic name from airsim.

@awaisali88 @nicovanduijn @HoaPham2711 @mingleeeeee I would be very grateful if you can also help me with the solution.

**Comment by Dprasad20** [comment]
@Yueting-Li Were you able to do so?
