### ISSUE TITLE
Algorithm Selection

### ISSUE THREAD

**Issue by alexcherpi** [PX4/avoidance#147]
Hi,

The PX4/avoidance uses the 3DVFH+ algorithm for obstacle avoidance while navigating.
This algorithm is based on a octomap (occupancy grid - octree), which is widely used in mapping, mainly because of its simplicity and low memory storage.

But recently the [Voxblox](https://voxblox.readthedocs.io/en/latest/index.html) algorithm for obstacle avoidance have been published and released with open-source [ROS implementation](https://voxblox.readthedocs.io/en/latest/pages/Running-Voxblox.html).
This algorithm is based on Signed Distance Field (SDF) and is shown that generating this SDF is [faster than constructing the octree](https://arxiv.org/abs/1611.03631), and then navigation algorithm are easier to do on SDF than on octree. 

What do you think? Why did you choose 3DVFH+ instead of Voxblox?

Many thanks,
Alexandre

**Comment by mhkabir** [comment]
The development of this package started internally long before the release and prevalence of SDF based state of the art methods.

Contributions to allow planning on a different world representation are welcome!
