### ISSUE TITLE
Error when running "rosrun mavros mavsafety arm"

### ISSUE THREAD

**Issue by BreederBai** [PX4/avoidance#159]
As the title says, when I run this command, something goes wrong.The error message is as follows

> Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/mavros/mavsafety", line 18, in <module>
    from mavros import command
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/mavros/command.py", line 23, in <module>
    from mavros_msgs.srv import CommandLong, CommandInt, CommandBool, CommandHome, CommandTOL, CommandTriggerControl, CommandTriggerInterval
ImportError: cannot import name CommandTriggerInterval

The operating system I am using is ubuntu16.04."rosrun mavros mavsys mode -c OFFBOARD" can execute successfully.The simulation interface can also display normally.

**Comment by mrivi** [comment]
@BreederBai  `dpkg -s ros-kinetic-mavros | grep -i version` and `dpkg -s ros-kinetic-mavlink | grep -i version`
