### ISSUE TITLE
problems on run the simulation

### ISSUE THREAD

**Issue by gitdetector** [PX4/avoidance#171]
When I run `roslaunch local_planner local_planner_stereo.launch`, there will be a problem

> gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -e ode /home/h/catkin_ws/src/avoidance/local_planner/../sim/worlds/simple_obstacle.world.

but when I change the world to empty.world of PX4 Firmware, no error.
Is it because of the version of gazebo or gazebo_ros_packages different ?
Thanks in advance.

**Comment by mrivi** [comment]
fixed with #174
