### ISSUE TITLE
[Err] [RTShaderSystem.cc:489] Unable to find shader lib. Shader generating will fail

### ISSUE THREAD

**Issue by Sunshinehualong** [PX4/avoidance#177]
## when I run  `make px4_sitl_default gazebo` 

 
![screenshot from 2019-01-15 22-41-58](https://user-images.githubusercontent.com/26672004/51187442-d2e97180-1916-11e9-9544-2dfd75f8c550.png)

**Comment by mrivi** [comment]
`export GAZEBO_RESOURCE_PATH=/usr/share/gazebo-7.0` . You need to change the gazebo version to match what you have installed

**Comment by Sunshinehualong** [comment]
Thank you mrivi
It's really solved the problem.

**Comment by ibrahimqazi** [comment]
@Sunshinehualong I have exactly the same error. Can you please guide me how to solve it? I have Gazebo multi-robot simulator, version 7.14.0

**Comment by ibrahimqazi** [comment]
@mrivi can you please guide I have same error and my gazebo version is also 7.14.0.

**Comment by nicovanduijn** [comment]
If you have exactly the same error, I would suggest exactly the same solution...?

**Comment by ibrahimqazi** [comment]
@nicovanduijn he said to change the gazebo version, so change means upgrade or downgrade? By the way I am not PX4 package rather using another package but the problem is same as given above.

**Comment by nicovanduijn** [comment]
It means you should set your `GAZEBO_RESOURCE_PATH` correctly. Depending on what version of gazebo  you are running.
If you are running gazebo 7.0, run `export GAZEBO_RESOURCE_PATH=/usr/share/gazebo-7.0`.
