### ISSUE TITLE
Questions regarding planners

### ISSUE THREAD

**Issue by SwiftGust** [PX4/avoidance#201]
I've running avoidance simulations of both planners

I found that global planner works great and capable of real-time mapping and 3D path planning with rough scaled octomap and the path smoothing.
Also, planning may fail but it mostly keep drone from collisions
so the result in gazebo simulation is very desirable and satisfactory.

Whereas the local planner, It usually finds way in 2D, slowly progresses and often collide into trees or terrains and sometimes it goes around trees like forever due to it does not record previous point clouds
and computation in my desktop is also heavy (probably due to lots of visualization in RViz)

I wonder why only local planner is available for running on hardware such as Intel Aero RTF
and dev team focuses are in local planner, not the global planner

Thanks in advance.

**Comment by jkflying** [comment]
As Nico said, the global planner was never tested on real hardware and it seems nobody wants to be the first! Another thing to consider is that in a small area like a SITL map the RAM requirements of the global planner might be fine, but over a ~5km flight (or more) it might not work as well.

This said, the global planner is very promising and we would definitely like to have it working in the future!
