### ISSUE TITLE
make px4_sitl_default gazebo fails to build

### ISSUE THREAD

**Issue by magiccreator69** [PX4/avoidance#217]
Hello,
I'm a beginner in px4, ROS, and Gazebo. My target is to deploy this program on jetson tx2. But before that, I want to try the offboard simulator on my desktop. 
Followed the steps mentioned in this repository and installed all the dependencies. 
OS: Ubuntu 16.04
ROS-Kinetic
Gazebo 9
After I do "make px4_sitl_default gazebo", it opens a new Gazebo window and freezes making the program at "EKF commencing GPS fusion". I got no idea where should I start from as I can't run the program unless I've built it successfully. Am I supposed to create obstacles in the Gazebo simulator myself and provide the file path to the program? Thanks in advance.

![screenshot from 2019-02-12 22-01-40](https://user-images.githubusercontent.com/43385355/52640642-e980e980-2f11-11e9-939c-889c7fe206d4.png)

![screenshot from 2019-02-12 21-49-47](https://user-images.githubusercontent.com/43385355/52640686-fef61380-2f11-11e9-8046-e647ea37b9e0.png)

**Comment by dagar** [comment]
You should be seeing a quadcopter (3dr iris) in the Gazebo window.

**Comment by dagar** [comment]
@TSC21 any ideas?

**Comment by magiccreator69** [comment]
Yes, I can see the quadcopter which is comparatively small in size that's why can't be seen in the picture I've attached here. What do I need to do now?

**Comment by mrivi** [comment]
@magiccreator69 if you have the ROS already installed you need to follow the instructions on how to run the local or global planner (https://github.com/PX4/avoidance#run-the-avoidance-gazebo-simulation)

If you don't have ROS installed please follow [these instructions](https://github.com/PX4/avoidance#installation-for-ubuntu-1604-and-ros-kinetic)

**Comment by julianoes** [comment]
This looks stale, please re-open if it's still an issue.

**Comment by mta32** [comment]
Was the issue resolved ?? Where you able to simulate obstacle avoidance after adding an obstacle
