### ISSUE TITLE
Error [parser.cc:689] Unable to find uri[model://iris]

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#262]
Error [parser.cc:689] Unable to find uri[model://iris]

**Comment by mrivi** [comment]
@lioneleeedadad please follow these instructions https://github.com/PX4/avoidance#build-and-run-the-simulator

**Comment by lioneleeedadad** [comment]
One more thing , is there any issue in this package or should it work normally with no errors and give me the path planning I need ?

**Comment by mrivi** [comment]
@lioneleeedadad You need to adapt this line based on the location of the PX4 Firmware folder in your setup.

**Comment by lioneleeedadad** [comment]
I copy in one line
. ~catkin_ws/src/Firmware/Tools/setup_gazebo.bash ~catkin_ws/src/Firmware ~catkin_ws/src/Firmware/build/px4_sitl_default

the output is
bash: ~catkin_ws/src/Firmware/Tools/setup_gazebo.bash: No such file or directory

**Comment by lioneleeedadad** [comment]
@mrivi 
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:~/catkin_ws/src/avoidance/sim/models
should this line be copied as it is or I should adjust it ?

**Comment by mrivi** [comment]
@lioneleeedadad I think it should be
`. ~/catkin_ws/src/Firmware/Tools/setup_gazebo.bash ~/catkin_ws/src/Firmware ~/catkin_ws/src/Firmware/build/px4_sitl_default `

It should as it is if the avoidance repository is in `~/catkin_ws/src/avoidance`

**Comment by lioneleeedadad** [comment]
It worked ! THANK YOU .. YOU ARE GREAT!
