### ISSUE TITLE
RQT configure is opening but blank . how can I solve that ?

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#267]

**Comment by mrivi** [comment]
@lioneleeedadad you need to click on "local_planner_node` in the left column of the rqt reconfigure pop-up

**Comment by lioneleeedadad** [comment]
@mrivi Nothing is appearing in the rqt_configure at all .. I can't even find the local_planner_node

**Comment by lioneleeedadad** [comment]
@mrivi  Same problem :(

**Comment by Omar1710** [comment]
@jkflying its not solved !!

**Comment by jkflying** [comment]
This isn't an issue with Avoidance, I think. Have you managed to get RQT-reconfigure to work for anything else?

**Comment by lioneleeedadad** [comment]
Actually No :S I'm new to ROS and Gazebo so that's my first project and the first time to use RQT-reconfigure
