### ISSUE TITLE
Please the https://github.com/SyrianSpock/realsense_gazebo_plugin.git is not supported for ROS kinetic and I need the realsense how can I download it !?

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#275]

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad 

Please do not post usage questions in the git issue. The github issue is for reporting code related bugs / issues.

You can post usage questions in
- Px4 discuss:  http://discuss.px4.io/
- px4 slack: https://slack.px4.io/

You won't be able to get replies on usage questions here.

**Comment by lioneleeedadad** [comment]
Okay
