### ISSUE TITLE
Document simulation setup in PX4 dev guide

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/avoidance#28]
This would assume that the repo is in shape to be publishable.

**Comment by LorenzMeier** [comment]
@mrivi Still pending?

**Comment by hamishwillee** [comment]
FYI, draft docs for this in user guide are https://github.com/PX4/px4_user_guide/pull/375 and https://github.com/PX4/px4_user_guide/pull/376

**Comment by mrivi** [comment]
already done
