### ISSUE TITLE
global_planner and local_planner

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#283]
Dear people 
I have a question
what kind of path planning is used for global path planning and local path planning ?

**Comment by baumanta** [comment]
this is not an issue

**Comment by lioneleeedadad** [comment]
@baumanta hello baumanta yes but I saw the same question in the closed issues and there was other questions .. also this question will help other users

**Comment by lioneleeedadad** [comment]
@baumanta also I intend to ask here as it takes too much time to get a reply on px4 discussion

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad You will not get an answer here. And as you said, this is a duplicate question, so please refer to the answers that already exist. 

Please use discuss to ask questions and use this thread for issues only.
