### ISSUE TITLE
Global planner: Why is world frame reference frame?

### ISSUE THREAD

**Issue by TobiMiller** [PX4/avoidance#288]
Hey,

actually i am working on a project with your global planner avoidance. Is there a reason why you use the world instead of the local_origin frame? 
in my simulation the local_origin is not the same like gazebos world frame because my iris model is not spawning in (0,0,0). 
i have also implemented a switch to disable the avoidance from publishing setpoints so i can send my setpoints when needed. 
the problem: the move_base_simple/goal position differs from my setpoints which are referenced to local_origin.
actually i need to do a lookup from world to local_origin to transform from one frame to the other. that's nasty

best regards

**Comment by mrivi** [comment]
@TobiMiller it's for historical reasons. No one is currently developing the global planner so it stayed that way.
