### ISSUE TITLE
local_planner_node_main syntax error

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#290]
rosrun local_planner local_planner_node_main.cpp
/home/omar/catkin_ws/src/avoidance/local_planner/src/nodes/local_planner_node_main.cpp: line 8: syntax error near unexpected token `('
/home/omar/catkin_ws/src/avoidance/local_planner/src/nodes/local_planner_node_main.cpp: line 8: `int main(int argc, char** argv) {'
this error is in the node when I try to run it alone

**Comment by Jaeyoung-Lim** [comment]
The rosrun command should be 
```
rosrun <package_name> <node_name>
```
Therefore, your ron run command is not correct. There are proper instructions in the README on how to launch the local_planner node

**Comment by lioneleeedadad** [comment]
I only need to run this node

**Comment by lioneleeedadad** [comment]
rosrun local_planner local_planner_node_main.cpp 
I need to run the local_planner_node_main . to modify on it

**Comment by Jaeyoung-Lim** [comment]
`local_planner_node_main.cpp` is not a node. It is the source code for the node.

Can you explain why you need to 'only' run the main function?

**Comment by lioneleeedadad** [comment]
forsure .. I need to connect the local path planner to a publisher node . So I thought that the node which should be a subscriber is the local_planner_node_main

**Comment by lioneleeedadad** [comment]
What is the node that I could use to subscribe to a topic ?

**Comment by Jaeyoung-Lim** [comment]
A node cannot be a subscriber. If you simply want to control the drone using ROS topics, you can use [mavros](https://github.com/mavlink/mavros)

**Comment by lioneleeedadad** [comment]
why can't it subscribe to a topic ?

**Comment by Jaeyoung-Lim** [comment]
The node itself subscribes to topics. If you want the `local_planner` to subscribe to a new topic, you need to modify the source code

I think you are confused on how ROS works in general. Following a ROS tutorial and writing a simple node will let you better understand what a node, subscriber is and how it works with the local planner

**Comment by lioneleeedadad** [comment]
No i just need one node to subscribe to this topic not the hole local_planner .

**Comment by lioneleeedadad** [comment]
I'm thinking of local_planner_node to subscribe to that topic . I just need the local planner node to print hello world

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad In that case writing a new node for your own porpose would be a better solution

**Comment by lioneleeedadad** [comment]
I did them all :D

**Comment by lioneleeedadad** [comment]
and I know how to do node

**Comment by lioneleeedadad** [comment]
I just need to publish on a local path planning node to control it either to switch it on or off

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad Then you need to modify the source code of the local_planner

**Comment by lioneleeedadad** [comment]
which one is the source code ?

**Comment by lioneleeedadad** [comment]
all what I'm looking forward to is a publisher which publisher messages to say chatter topic and this message is either 0 or 1 if its 0 local path planning will be turned off and a teleop node will work if it is 1 local path path planning will work

**Comment by lioneleeedadad** [comment]
and this 0 or 1 is sensor signals

**Comment by Jaeyoung-Lim** [comment]
@lioneleeedadad You need to write your own package for that. http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29 this tutorial can be useful for you

**Comment by lioneleeedadad** [comment]
I want to utilize this package to do that

**Comment by Jaeyoung-Lim** [comment]
As I said, you need to reprogram this package

**Comment by lioneleeedadad** [comment]
yes I'm working on that

**Comment by lioneleeedadad** [comment]
however which source files should I edit ?

**Comment by Jaeyoung-Lim** [comment]
https://github.com/PX4/avoidance/blob/master/local_planner/src/nodes/local_planner_node.cpp#L52 This is where the subscribers are initialized in the local_planner

**Comment by lioneleeedadad** [comment]
Okay then I need to write the subscriber node then to initialize it using this node you just mentioned ?

**Comment by mhkabir** [comment]
Please move to Discuss.
