### ISSUE TITLE
How can I send a sequence of goals from a python package?

### ISSUE THREAD

**Issue by 20chix** [PX4/avoidance#291]
Hi

I was wondering how can I send a sequence of goals from a python package? I have tried to publish a PointStamped into /global_goal, but nothing. I can see my point when I echo the topic but nothing happening in Gazebo or Rviz.

Thanks in advance

**Comment by Jaeyoung-Lim** [comment]
@20chix 

This is more of a usage question regarding mavros rather than a issue on this repo. You can look at documentations such as [this](https://dev.px4.io/en/ros/mavros_offboard.html)

If this doesn't help, Please move this discussion to http://discuss.px4.io/

**Comment by 20chix** [comment]
Thanks
