### ISSUE TITLE
Unable to locate "px4.launch"

### ISSUE THREAD

**Issue by ElderWanng** [PX4/avoidance#300]
According to `mavros_sitl.launch`
`<include file="$(find px4)/launch/px4.launch">`t  this line
ros go into package `px4` and find `px4.launch`

But px4 firmware doesn't have px4.launch in `V1.8` (recommended by the README.MD of this repo )

I know avoidance can't work with the master branch of `Firmware`. ( the drone can't be armed in mater )
Hence, how to solve this conflict?

**Comment by mrivi** [comment]
@ElderWanng The avoidance does work with the latest Firmware master. Please use that. 1.8 is quite old and it doesn't support all the avoidance features (e.g. avoidance in mission mode)
