### ISSUE TITLE
Subscribing issue 

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#318]
I know this is not the right place to ask such a question .. however there are legends here so I need there help as I can't find any support in the discuss.px4.io .. so please help me :) ! I used the local_planner_node.cpp and the local_planner_node.h to subscribe to a topic and I'm now able to subscribe to that topic however when I use rosnode info /local_planner_node I find that topic[unknown] . and when I rosrun the node containing the publisher I'm not able to receive the message . So please what can I do with that ?
Thanks in advance ..

**Comment by mrivi** [comment]
This is not a issue of the avoidance package
