### ISSUE TITLE
MarkerArray does not show up

### ISSUE THREAD

**Issue by ElderWanng** [PX4/avoidance#320]
**Describe the bug**
Marker array (/occupied_cells_vis_array) does not show up when I try to run `global_planner_stereo.launch`

**To Reproduce**
Just run global_planner_stereo.launch in my laptop ( Ubuntu 18, melodic )

**Expected behavior**
The black boxes represent buildings doesn't show up 
But when I run `global_planner_sitl_mavros` It worked fine

**Log Files and Screenshots**
![ global_planner_sitl_mavros](https://user-images.githubusercontent.com/23718571/56474483-140c9700-64ad-11e9-9f97-c903b83577b1.png)
look, everything work well in this launch file(global_planner_sitl_mavros) 

but when I switched to `global_planner_stereo`, It doesn't display the barriers as I expected
![2019-04-22 02-57-54屏幕截图](https://user-images.githubusercontent.com/23718571/56474506-71084d00-64ad-11e9-8d78-9072e9673da4.png)

How can I run the simulation of stereo camera avoidance?

**Comment by mrivi** [comment]
@ElderWanng - the only working simulation for the global planner is global_planner_sitl_mavros.launch . 
If you would like to have a stereo camera simulation you can look at how it's done for the local_planner (local_planner_stereo.launch) and contribute it to the global planner.
