### ISSUE TITLE
Local Planner error 

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#321]
[ WARN] [1555955132.554677745, 4.644000000]: failed to visualize RViz dron marker
rviz opens in local planner but doesn't show trees neither 2D navigation goal . Also when I use rosrun mavros mavsys mode -c OFFBOARD . I get Timed out!

**Comment by ElderWanng** [comment]
same question with you in "Gazebo7, ros-kinetic, firmware master branch, and avoidance "

**Comment by lioneleeedadad** [comment]
Do you mean ?

**Comment by julianoes** [comment]
Please supply the steps you did and the full console output and paste it within ```. Otherwise this is not reproducible for us.

**Comment by lioneleeedadad** [comment]
I solved the problem thanksalot .. I now just have a question , what is the node responsible for controlling the speed of the four motors ?
