### ISSUE TITLE
launching global planner error

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#339]
[spawn_model-9] process has died [pid 15299, exit code 1, cmd /opt/ros/kinetic/lib/gazebo_ros/spawn_model -sdf -database iris_depth_camera -model iris __name:=spawn_model __log:=/home/omar/.ros/log/b76be5c2-7010-11e9-bf3c-e82a44e20f6f/spawn_model-9.log].
log file: /home/omar/.ros/log/b76be5c2-7010-11e9-bf3c-e82a44e20f6f/spawn_model-9*.log

**Comment by nicovanduijn** [comment]
Please
