### ISSUE TITLE
Quesntion on ThreePointMsg.msg support

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/avoidance#354]
`ThreePointMsg.msg` used in `global_planner/path_handler_node` seems to be doing something [quite similar](https://github.com/PX4/avoidance/blob/master/global_planner/src/nodes/path_handler_node.cpp#L312
) to what `mavros_msgs/trajectory` is sending. 

Would it make sense to depricate `ThreePointMsg` in global planner? or is there a reason that this is needed?

**Comment by mhkabir** [comment]
What was the conclusion here?

**Comment by mrivi** [comment]
@Jaeyoung-Lim  why did you close the issue? 
`ThreePointMsg` is old  message that was never upstreamed. It can be removed

**Comment by Jaeyoung-Lim** [comment]
@mrivi @mhkabir I was confused on what it was actually doing, so closed it so that I wanted to better understand what it is doing.

So, I need some help here, `ThreePointMsg` seems to be used to communicate between the `global_planner_node` and `path_handler_node`. Do you mean that this interface is not being used anymore?

**Comment by mrivi** [comment]
@Jaeyoung-Lim  I am going by memory here but if I remember correctly it's published but not used anywhere.

**Comment by Jaeyoung-Lim** [comment]
@mrivi Okay, that's a good hint. I will look more into it. I guess it makes sense to deprecate it if it is not used.
