### ISSUE TITLE
Common tests don't compile and aren't run in CI

### ISSUE THREAD

**Issue by nicovanduijn** [PX4/avoidance#356]
Currently, the tests in `avoidance/test` don't compile and are not run in CI

To reproduce:
```
cd avoidance
catkin run_tests --this --no-deps
```

Output:
![image](https://user-images.githubusercontent.com/14265408/57767456-ae0cdb80-7709-11e9-8167-7d42d2751c93.png)

I believe the CMakeLists.txt need to include histogram.h, but I don't want to introduce a dependency of common to the local planner. (Which would yield circular dependency)

Not sure why these tests need `histogram.h` anyway

@Jaeyoung-Lim Any ideas?

**Comment by Jaeyoung-Lim** [comment]
@nicovanduijn Wow that is me screwing up. Thanks for pointing this out.

I will have a look. I suspect it is only depending on it in the test function
