### ISSUE TITLE
Question on /mavros/trajectory/desired msgs

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/avoidance#388]
Looking at the implementations passing the `/mavros/trajectory/desired` points, we are only using the first point to send to the FCU.

 https://github.com/PX4/avoidance/blob/master/avoidance/src/common.cpp#L267-L291

Is this due to a limitation of PX4 not being able to follow paths properly? or is this simply a hack to enforce the position controller to follow the first point as desired?

**Comment by nicovanduijn** [comment]
Correct, the interface was created with generality in mind - hoping that one day we could have proper trajectory following on the PX4 side. 

It is indeed a waste of bandwidth, sending 80 doubles or so, at a rate of 30Hz.. When all we really compute are 4 floats
