### ISSUE TITLE
Collision Prevention without local planner

### ISSUE THREAD

**Issue by hansbonini** [PX4/avoidance#389]
Hi guys, i'm trying to configure de collision prevention over the obstacle avoidance module in PX4.
I've remapped my guidance obstacle distance topic to "/mavros/obstacle/send" and setted the parameter MPC_COL_PREV_D on the FCU.

There are more topics to publish? Or only these one ("/mavros/obstacle/send") is needed?
Can anybody give me a path? What i forget'd?

Kind Regards
Hans Bonini

**Comment by mrivi** [comment]
You only need to send distance data trough that topic and you are good to go. Then start your rosnode, switch into position control, control the vehicle with a gamepad.

**Comment by hansbonini** [comment]
@mrivi i will try here. thank you so much for clear my doubts.

**Comment by bhaskar-glitch** [comment]
> @mrivi i will try here. thank you so much for clear my doubts.

Hi @hansbonini Did u tried the same on drone?
