### ISSUE TITLE
raspberry pi supported?

### ISSUE THREAD

**Issue by nickxdxd** [PX4/avoidance#409]
will it work for a hobbyist drone using raspberrypi as a ros platform?

**Comment by Jaeyoung-Lim** [comment]
@nickxdxd I have not seen it work on the raspberry pi yet, but would be really excited to see it working on it

**Comment by jkflying** [comment]
With the release of the new RaspberryPi 4 there is definitely enough power there to run the Planner. The issue is that we need to get ROS running on it first, but I'm sure the community will get that to happen quickly.
