### ISSUE TITLE
gazebo-7 process has died ...when trying to launch global_planner

### ISSUE THREAD

**Issue by ramb182k** [PX4/avoidance#414]
![Screenshot from 2019-06-19 17-16-01](https://user-images.githubusercontent.com/50549258/59763008-2d1ba380-92b6-11e9-80c1-194bc03282d3.png)
i dont know why this happens and can you tell me a solution...thank you :)

**Comment by Jaeyoung-Lim** [comment]
Have you tried just running the SITL gazebo simulation without avoidance?

**Comment by ramb182k** [comment]
yes it launches and i find a drone
