### ISSUE TITLE
RealSense D430 module supported? (non-RGB D435)

### ISSUE THREAD

**Issue by NicksonYap** [PX4/avoidance#415]
Hi!

I just found out about the RealSense D430 module (with the same USB-C connection as D435)

It seems that D430 is the same module used inside D435, with additional RGB camera.

(not my pic)
![image](https://user-images.githubusercontent.com/5380731/59820194-7a068500-935d-11e9-9f55-ac7b27ea5233.png)

![image](https://user-images.githubusercontent.com/5380731/59820955-ff8a3500-935d-11e9-9c7c-6e70c118bcaf.png)

![image](https://user-images.githubusercontent.com/5380731/59820600-e84b4780-935d-11e9-9451-5da8b9aa25d1.png)

It's has a much smaller form factor and can be separated from the main sensor circuitry
It's also 30-40% cheaper...

Does the repo depend on RGB input, depth only or both?
such that we can use the non-RGB D430 instead
What would be needed to be configured in the software?

Best Regards

Nickson
Founder
[seamlesshq.com](http://url)

**Comment by mrivi** [comment]
@NicksonYap - All planners require a pointCloud as input. We don't have any other requirement

**Comment by NicksonYap** [comment]
@mrivi
Ah yes
To be specific, they are xyz point clouds
non-rgb right?

**Comment by mhkabir** [comment]
@NicksonYap yes.

**Comment by kafan1986** [comment]
@NicksonYap Where did you get the D400 interposer ribbon cable from?

**Comment by bsprime** [comment]
> Hi!
> 
> I just found out about the RealSense D430 module (with the same USB-C connection as D435)
> 
> It seems that D430 is the same module used inside D435, with additional RGB camera.
> 
> (not my pic)
> ![image](https://user-images.githubusercontent.com/5380731/59820194-7a068500-935d-11e9-9f55-ac7b27ea5233.png)
> 
> ![image](https://user-images.githubusercontent.com/5380731/59820955-ff8a3500-935d-11e9-9c7c-6e70c118bcaf.png)
> 
> ![image](https://user-images.githubusercontent.com/5380731/59820600-e84b4780-935d-11e9-9451-5da8b9aa25d1.png)
> 
> It's has a much smaller form factor and can be separated from the main sensor circuitry
> It's also 30-40% cheaper...
> 
> Does the repo depend on RGB input, depth only or both?
> such that we can use the non-RGB D430 instead
> What would be needed to be configured in the software?
> 
> Best Regards
> 
> Nickson
> Founder
> [seamlesshq.com](http://url)

@NicksonYap where did you get interposer ribbon cable.
