### ISSUE TITLE
OFFBOARD Timed out!, No GPS fix

### ISSUE THREAD

**Issue by optimize0107** [PX4/avoidance#427]
Hello.. help me plz.. i'm tired. I reinstalled ubuntu 7 times..

ubuntu 16.04
Gazebo7
ROS Kinetic

1. If 'roslaunch~~' first
    (1) Can't see drone, stereo images in Rviz, Gazebo
    (2) No GPS fix(and i can't use 'commander takeoff')
    (3) Timed out!. when use 'mode -c OFFBOARD'

2. If 'make px4~~' first
    (1) Can see drone in Gazebo, Can activate 'fcu', 'Vehicle pose' in Rviz(but can't see drone)
    (2) Can't see trees
    (3) Cant' synchronize time between Gazebo, Rviz(but i can use 'commander takeoff')
    (3) Timed out!. when use 'mode -c OFFBOARD'

===============================================================
If  run 'roslaunch' first, (I heard that 'make px4~~'is not nessesary)
- [terminal 1]
       
      roslaunch global_planner global_planner_stereo.launch
     
    then some trees show up, but there's no drone. And 'No GPS fix' warning
      ![1](https://user-images.githubusercontent.com/41814103/60591632-d3e56100-9dd9-11e9-8089-707cb5e56010.png)

- [terminal 2]
![2](https://user-images.githubusercontent.com/41814103/60591469-7bae5f00-9dd9-11e9-8468-1a248fd10e5b.png)

- [terminal 3]
     I can't see the drone in the gazebo too
![3](https://user-images.githubusercontent.com/41814103/60591885-5ff78880-9dda-11e9-917b-1a68d01c268c.png)

![4](https://user-images.githubusercontent.com/41814103/60592072-caa8c400-9dda-11e9-8571-dd56e762aa06.png)
If use 'commander takeoff' in PX4, 
![fff](https://user-images.githubusercontent.com/41814103/60594084-22e1c500-9ddf-11e9-9d89-84d52b69bb60.png)

- When i ready for this simulation. I used(I downloaded 'Firmware' to ~/catkin_ws/src/Firmware, not ~/Firmware)

      . ~/catkin_ws/src/Firmware/Tools/setup.bash ~/catkin_ws/src/Firmware ~/catkin_ws/src/Firmware/build/px4_sitl_default
   
      export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:~catkin_ws/src/Firmware
     
      echo export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:~/catkin_ws/src/avoidance/avoidance/sim/models:~/catkin_ws/src/avoidance/avoidance/sim/worlds >> ~/.bashrc
      

===============================================================
If  run 'make px4' first,
- [terminal 1]
![a](https://user-images.githubusercontent.com/41814103/60592904-8a4a4580-9ddc-11e9-8ce3-fcdd432b5d69.png)

- [terminal 2]
![b](https://user-images.githubusercontent.com/41814103/60593064-ef05a000-9ddc-11e9-9abe-d5a623f3e5ca.png)
![c](https://user-images.githubusercontent.com/41814103/60593066-f167fa00-9ddc-11e9-998b-40b4f6f7b0b3.png)
![d](https://user-images.githubusercontent.com/41814103/60593186-2d9b5a80-9ddd-11e9-9b7c-926dbe1307c2.png)

I can see 'fcu' and 'Vehicle pose', but i can't see these when i started 'roslaunch' first.
No matter how long i wait, Rviz Time is not connected to Gazebo Time(Radeon RX580, Ryzen 5 2600, 16GB RAM). But strangley, when i use 'commander takeoff' in PX4, both Gazebo and Rviz screens are move up. If i run 'mode -c OFFBOARD', 'Timed out!' show up.

![g](https://user-images.githubusercontent.com/41814103/60593461-c336ea00-9ddd-11e9-8712-ed792b93ea26.png)
================================================================

 **I really want to see this!**
![fff](https://user-images.githubusercontent.com/41814103/60594216-6805f700-9ddf-11e9-8dda-250dc8783167.png)

**Comment by mrivi** [comment]
@optimize0107 `roslaunch global_planner global_planner_stereo.launch` already launches PX4 sitl. You don't need to run `make px4_sitl gazebo` as well.
You have to run `make px4_sitl gazebo` once to build the Firmware. Then you stop the simulation and run only `roslaunch global_planner global_planner_stereo.launch`

**Comment by optimize0107** [comment]
@mrivi Yes i read that in other issue. But running 'make px4_sitl gazebo' was just for checking drone

My problem is that when I run only 'roslaunch global_planner global_planner_stereo.launch ',
1) I can't sea drone in Rviz.
2) No GPS fix  warning.
3) Can't change mode to OFFBOARD by timed out error

**Comment by mrivi** [comment]
@optimize0107 - Could you please share the output of `echo` on the following environment variables in the terminal where you're trying to run the global planner
- ROS_PACKAGE_PATH
- GAZEBO_MODEL_PATH
- GAZEBO_RESOURCE_PATH
- GAZEBO_PLUGIN_PATH
- LD_LIBRARY_PATH

**Comment by optimize0107** [comment]
@mrivi WOW.  I can simulate global_planner. Thanks!
I don't know exact reason. But I think PATH was the problem. 
I downloaded 'Firmware' at '~/catkin_ws/src/Firmware'. So I deleted them(Files in 'build', 'src' related to 'Firmware') and do same things with '~/Firmware'. 
![ffffffffffffff](https://user-images.githubusercontent.com/41814103/60639427-a2ae7480-9e5d-11e9-944e-29b4dc518cd2.png)

**Comment by aydal** [comment]
Hello @mrivi

**Comment by siyuada** [comment]
@aydal Hey, I got the same issue, and fixed by add px4 lib path to ~/.bashrc.
add the line below to your ~/.bashrc, and change the abs path.
`
export LD_LIBRARY_PATH=:/home/uav514/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/uav514/Firmware/Tools/setup_gazebo.bash:/home/uav514/Firmware:/home/uav514/Firmware/build/px4_sitl_default
`

Hope it helps.
