### ISSUE TITLE
issue when build the catkin

### ISSUE THREAD

**Issue by onionysy** [PX4/avoidance#484]
We use GitHub issues only to discuss PX4 Avoidance bugs and new features. For
questions about using PX4 or related components, please use [PX4 Discuss](http://discuss.px4.io/).
when i build the catkin. there is a warning in the process.
i want to know if it will influence the result, or how can i resolve it. 
thank you!

`Workspace configuration appears valid.
----------------------------------------------------------------
[build] Found '4' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Starting  >>> avoidance                                                        
Finished  <<< avoidance                           [ 0.6 seconds ]              
Starting  >>> global_planner                                                   
Starting  >>> local_planner                                                    
Starting  >>> safe_landing_planner                                             
Finished  <<< local_planner                       [ 30.6 seconds ]             
Finished  <<< safe_landing_planner                [ 31.2 seconds ]             
_______________________________________________________________________________
Warnings   << global_planner:make /home/coamc/avoid_catkin_ws/logs/global_planner/build.make.003.log
In file included from /opt/ros/melodic/include/ros/ros.h:40:0,
                 from /opt/ros/melodic/include/pcl_conversions/pcl_conversions.h:42,
                 from /home/coamc/avoid_catkin_ws/src/avoidance/global_planner/include/global_planner/global_planner_node.h:16,
                 from /home/coamc/avoid_catkin_ws/src/avoidance/global_planner/src/nodes/global_planner_node.cpp:1:
/home/coamc/avoid_catkin_ws/src/avoidance/global_planner/src/nodes/global_planner_node.cpp: In member function ‘void global_planner::GlobalPlannerNode::depthCameraCallback(const PointCloud2&)’:
/opt/ros/melodic/include/ros/console.h:348:176: warning: format ‘%s’ expects argument of type ‘char*’, but argument 8 has type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ [-Wformat=]
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                                ^
/opt/ros/melodic/include/ros/console.h:351:5: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER’
     ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER(NULL, __VA_ARGS__)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/melodic/include/ros/console.h:387:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION’
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/melodic/include/ros/console.h:572:35: note: in expansion of macro ‘ROS_LOG_COND’
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^~~~~~~~~~~~
/opt/ros/melodic/include/rosconsole/macros_generated.h:162:23: note: in expansion of macro ‘ROS_LOG’
 #define ROS_WARN(...) ROS_LOG(::ros::console::levels::Warn, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
                       ^~~~~~~
/home/coamc/avoid_catkin_ws/src/avoidance/global_planner/src/nodes/global_planner_node.cpp:294:5: note: in expansion of macro ‘ROS_WARN’
     ROS_WARN("Transformation not available (%s to /camera_link", frame_id_);
     ^
cd /home/coamc/avoid_catkin_ws/build/global_planner; catkin build --get-env global_planner | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
`

Thanks!

**Comment by mrivi** [comment]
They are warning on the ROS logging console outputs. They don't have any influence on the planner itself.
