### ISSUE TITLE
issue when run the global_planner

### ISSUE THREAD

**Issue by onionysy** [PX4/avoidance#486]
Thank for the excellent 'avoidance' project.
i have run the local_planner successfully, but when i run `rosrun mavros mavsafety arm`, the cammand shows:
`coamc@coamc-HP-Z840-Workstation:~$ rosrun mavros mavsafety arm
Request failed. Check mavros logs`
and
`WARN  [commander] Arming denied! Avoidance system not ready
[ERROR] [1568781066.666805554, 39.476000000]: FCU: Arming denied! Avoidance system not ready`

can you give me some advices?
thank you!

**Comment by mrivi** [comment]
@onionysy I can reproduce the problem, thanks for reporting. We'll look into it

**Comment by mrivi** [comment]
fixed in #488
