### ISSUE TITLE
Invalid Quaternion in transform at startup

### ISSUE THREAD

**Issue by mrivi** [PX4/avoidance#492]
We get a bunch of this errors at startup on all 3 planners. We need to figure out where are they coming from. 
``` bash 
[ERROR] [1569826119.454300726, 0.856000000]: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)

**Comment by mrivi** [comment]
I tried a few things:
- happens also with older versions of mavros e.g. 0.30.0
- doesn't happen on hardware

**Comment by hassaanhashmi** [comment]
Hi @mrivi , have you figured out why it happens in software?

**Comment by mrivi** [comment]
No, I didn't investigate further since they aren't creating any issues. We look further in the future.

**Comment by mrivi** [comment]
Figured out where it comes ffrom https://github.com/PX4/Firmware/issues/13182

**Comment by mrivi** [comment]
Fixed https://github.com/PX4/Firmware/pull/13184
