### ISSUE TITLE
cannot launch node of type [local_planner/local_planner_node];AND  An exception has been thrown: set_pu(id=4) failed! Last Error: Input/output error

### ISSUE THREAD

**Issue by dance-code** [PX4/avoidance#504]
Plz  help me.
My device:TX2; realsenceD435i;Ubuntu18.04
The bug:ERROR: cannot launch node of type [local_planner/local_planner_node]: can't locate node [local_planner_node] in package [local_planner]
                  WARNING [546961768832] (types.cpp:48) set_pu(id=4) failed! Last Error: 
 Input/output error
            [ERROR] [1570761015.187835699]: An exception has been thrown: set_pu(id=4) failed! Last Error: Input/output error

My steps:
I haven't face problem before creating the avoidance.launch.(I use /tools/generate_launchfile.sh.deprecated     generate  the  launch.)
But when I roslaunch the avoidance.launch. I face the fllowing problem.
 Anybody  can   help me?  plz.

**Log Files and Screenshots**
SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 0
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: False
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 0
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 0
 * /camera/realsense2_camera/gyro_fps: 0
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: /home/amov/avo_ws...
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /local_planner_node/goal_x_param: 0
 * /local_planner_node/goal_y_param: 0
 * /local_planner_node/goal_z_param: 4
 * /local_planner_node/pointcloud_topics: ['/camera/depth/p...
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: /dev/ttyTHS1:57600
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: local_origin
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: False
 * /mavros/mocap/use_tf: True
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    points_xyz_sw_registered (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    drop_camera_depth (topic_tools/drop)
    drop_camera_ir (topic_tools/drop)
    dynparam (dynamic_reconfigure/dynparam)
    local_planner_node (local_planner/local_planner_node)
    mavros (mavros/mavros_node)
    rqt_param_toggle (local_planner/rqt_param_toggle.sh)
    tf_camera (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[mavros-1]: started with pid [10693]
process[tf_camera-2]: started with pid [10694]
process[camera/realsense2_camera_manager-3]: started with pid [10695]
process[camera/realsense2_camera-4]: started with pid [10705]
process[camera/points_xyz_sw_registered-5]: started with pid [10707]
process[drop_camera_depth-6]: started with pid [10709]
process[drop_camera_ir-7]: started with pid [10715]
process[dynparam-8]: started with pid [10725]
ERROR: cannot launch node of type [local_planner/local_planner_node]: can't locate node [local_planner_node] in package [local_planner]
process[rqt_param_toggle-10]: started with pid [10732]
[ INFO] [1570761007.579687994]: Initializing nodelet with 4 worker threads.
[ INFO] [1570761007.770895663]: FCU URL: /dev/ttyTHS1:57600
[ INFO] [1570761007.776236322]: serial0: device: /dev/ttyTHS1 @ 57600 bps
[ INFO] [1570761007.780226989]: GCS bridge disabled
[ INFO] [1570761007.817903435]: Plugin 3dr_radio loaded
[ INFO] [1570761007.823011163]: Plugin 3dr_radio initialized
[ INFO] [1570761007.823804995]: Plugin actuator_control loaded
[ INFO] [1570761007.834853183]: Plugin actuator_control initialized
[ INFO] [1570761007.847087068]: Plugin adsb loaded
[ INFO] [1570761007.857124219]: Plugin adsb initialized
[ INFO] [1570761007.857631586]: Plugin altitude loaded
[ INFO] [1570761007.861004747]: Plugin altitude initialized
[ INFO] [1570761007.861397341]: Plugin cam_imu_sync loaded
[ INFO] [1570761007.863709837]: Plugin cam_imu_sync initialized
[ INFO] [1570761007.864471799]: Plugin command loaded
[ INFO] [1570761007.883463409]: Plugin command initialized
[ INFO] [1570761007.883762216]: Plugin companion_process_status loaded
[ INFO] [1570761007.892339912]: Plugin companion_process_status initialized
[ INFO] [1570761007.892654393]: Plugin debug_value loaded
[ INFO] [1570761007.910182747]: Plugin debug_value initialized
[ INFO] [1570761007.910346835]: Plugin distance_sensor blacklisted
[ INFO] [1570761007.910679595]: Plugin fake_gps loaded
[ INFO] [1570761007.938014824]: Plugin fake_gps initialized
[ INFO] [1570761007.938444183]: Plugin ftp loaded
[ INFO] [1570761007.962551124]: Plugin ftp initialized
[ INFO] [1570761007.962961475]: Plugin global_position loaded
[ INFO] [1570761008.015155787]: Plugin global_position initialized
[ INFO] [1570761008.015641960]: Plugin gps_rtk loaded
[ INFO] [1570761008.025024800]: Plugin gps_rtk initialized
[ INFO] [1570761008.025425414]: Plugin hil loaded
[ INFO] [1570761008.071545939]: Plugin hil initialized
[ INFO] [1570761008.071879533]: Plugin home_position loaded
[ INFO] [1570761008.083954812]: Plugin home_position initialized
[ INFO] [1570761008.084385265]: Plugin imu loaded
[ INFO] [1570761008.109222174]: Plugin imu initialized
[ INFO] [1570761008.109629974]: Plugin landing_target loaded
[ INFO] [1570761008.142632520]: Plugin landing_target initialized
[ INFO] [1570761008.143001785]: Plugin local_position loaded
[ INFO] [1570761008.171755471]: Plugin local_position initialized
[ INFO] [1570761008.172096303]: Plugin log_transfer loaded
[ INFO] [1570761008.194293473]: Plugin log_transfer initialized
[ INFO] [1570761008.194693045]: Plugin manual_control loaded
[ INFO] [1570761008.212826794]: Plugin manual_control initialized
[ INFO] [1570761008.213157159]: Plugin mocap_pose_estimate loaded
[ INFO] [1570761008.266573927]: Plugin mocap_pose_estimate initialized
[ INFO] [1570761008.266908354]: Plugin mount_control loaded
[ INFO] [1570761008.272718634]: Plugin mount_control initialized
[ INFO] [1570761008.273003224]: Plugin obstacle_distance loaded
[ INFO] [1570761008.278293847]: Plugin obstacle_distance initialized
[ INFO] [1570761008.278585884]: Plugin odom loaded
[ INFO] [1570761008.291675014]: Plugin odom initialized
[ INFO] [1570761008.292029853]: Plugin param loaded
[ INFO] [1570761008.299659585]: Plugin param initialized
[ INFO] [1570761008.299962610]: Plugin px4flow loaded
[ INFO] [1570761008.322237112]: Plugin px4flow initialized
[ INFO] [1570761008.322389744]: Plugin rangefinder blacklisted
[ INFO] [1570761008.322705319]: Plugin rc_io loaded
[ INFO] [1570761008.334024572]: Plugin rc_io initialized
[ INFO] [1570761008.334197253]: Plugin safety_area blacklisted
[ INFO] [1570761008.334505434]: Plugin setpoint_accel loaded
[ INFO] [1570761008.344363928]: Plugin setpoint_accel initialized
[ INFO] [1570761008.344733662]: Plugin setpoint_attitude loaded
[ INFO] [1570761008.370280719]: Plugin setpoint_attitude initialized
[ INFO] [1570761008.370656024]: Plugin setpoint_position loaded
[ INFO] [1570761008.408861394]: Plugin setpoint_position initialized
[ INFO] [1570761008.409225451]: Plugin setpoint_raw loaded
[ INFO] [1570761008.440523527]: Plugin setpoint_raw initialized
[ INFO] [1570761008.440898780]: Plugin setpoint_velocity loaded
[ INFO] [1570761008.455043160]: Plugin setpoint_velocity initialized
[ INFO] [1570761008.455464135]: Plugin sys_status loaded
[ INFO] [1570761008.481030252]: Plugin sys_status initialized
[ INFO] [1570761008.481537203]: Plugin sys_time loaded
[ INFO] [1570761008.494444226]: TM: Timesync mode: MAVLINK
[ INFO] [1570761008.498242897]: Plugin sys_time initialized
[ INFO] [1570761008.498675485]: Plugin trajectory loaded
[ INFO] [1570761008.513973901]: Plugin trajectory initialized
[ INFO] [1570761008.514399199]: Plugin vfr_hud loaded
[ INFO] [1570761008.516540735]: Plugin vfr_hud initialized
[ INFO] [1570761008.516876047]: Plugin vibration blacklisted
[ INFO] [1570761008.517227033]: Plugin vision_pose_estimate loaded
[ INFO] [1570761008.528416411]: RealSense ROS v2.2.5
[ INFO] [1570761008.528526081]: Running with LibRealSense v2.22.0
[ INFO] [1570761008.556368401]: Plugin vision_pose_estimate initialized
[ INFO] [1570761008.556680331]: Plugin vision_speed_estimate loaded
[ INFO] [1570761008.565778581]: Plugin vision_speed_estimate initialized
[ INFO] [1570761008.566178309]: Plugin waypoint loaded
[ INFO] [1570761008.575629056]: Plugin waypoint initialized
[ INFO] [1570761008.575759452]: Plugin wheel_odometry blacklisted
[ INFO] [1570761008.576030659]: Plugin wind_estimation loaded
[ INFO] [1570761008.577912184]: Plugin wind_estimation initialized
[ INFO] [1570761008.578098717]: Autostarting mavlink via USB on PX4
[ INFO] [1570761008.578213647]: Built-in SIMD instructions: ARM NEON
[ INFO] [1570761008.578294103]: Built-in MAVLink package version: 2019.9.9
[ INFO] [1570761008.580277279]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1570761008.580664822]: MAVROS started. MY ID 1.240, TARGET ID 1.1
 11/10 10:30:08,680 WARNING [546961768832] (types.cpp:48) hwmon command 0x4f failed. Error type: No data to return (-21).
[ INFO] [1570761008.700502138]: getParameters...
[ INFO] [1570761008.872352590]: setupDevice...
Waiting for service /camera/stereo_module/set_parameters...
Waiting for service /local_planner_node/set_parameters...
 11/10 10:30:15,186 WARNING [546961768832] (types.cpp:48) set_pu(id=4) failed! Last Error: Input/output error
[ERROR] [1570761015.187835699]: An exception has been thrown: set_pu(id=4) failed! Last Error: Input/output error
terminate called after throwing an instance of 'rs2::invalid_value_error'
  what():  set_pu(id=4) failed! Last Error: Input/output error
[camera/realsense2_camera_manager-3] process has died [pid 10695, exit code -6, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/amov/.ros/log/c174dd6e-ebce-11e9-bd46-d6828bb119a5/camera-realsense2_camera_manager-3.log].
log file: /home/amov/.ros/log/c174dd6e-ebce-11e9-bd46-d6828bb119a5/camera-realsense2_camera_manager-3*.log
[camera/points_xyz_sw_registered-5] process has finished cleanly
log file: /home/amov/.ros/log/c174dd6e-ebce-11e9-bd46-d6828bb119a5/camera-points_xyz_sw_registered-5*.log
[camera/realsense2_camera-4] process has finished cleanly
log file: /home/amov/.ros/log/c174dd6e-ebce-11e9-bd46-d6828bb119a5/camera-realsense2_camera-4*.log

**Comment by mrivi** [comment]
@dance-code  these are errors from the realsense driver. Please try google them or ask the intel team for support
