### ISSUE TITLE
Error：Tf has two or more unconnected trees

### ISSUE THREAD

**Issue by PonyZhou** [PX4/avoidance#505]
Hi, 

when I run local_planner_realsense.launch, the terminal shows error below:
**[ERROR] [1569999868.063794455]: ODOM: Ex: Could not find a connection between 'local_origin_ned' and 'fcu' because they are not part of the same tree.Tf has two or more unconnected trees.**

**Comment by TSC21** [comment]
That's not an avoidance issue but rather a MAVROS one. That's already fixed on MAVROS 0.33.0 release done yesterday, which should be available on the apt sources in the next weeks.

**Comment by PonyZhou** [comment]
Thanks for reply！
