### ISSUE TITLE
Could not retrieve requested transform from buffer. Pointcloud dropped

### ISSUE THREAD

**Issue by germal** [PX4/avoidance#521]
Hi,

I am trying to start  local_planner_aero  on Jetson Nano with :

- Intel Realsense d435 camera
- Pixhawk FMUv2  with firmware 1.9.0 or 1.9.2  ( I tried the built one from source or from QGC)
- ROS Melodic 
- Mavros master -> 0.33.0
- Mavlink  2019.10.10

**roslaunch local_planner local_planner_aero.launch**

SUMMARY
========

PARAMETERS
 * /local_planner_node/goal_x_param: 0
 * /local_planner_node/goal_y_param: 0
 * /local_planner_node/goal_z_param: 4
 * /local_planner_node/pointcloud_topics: ['/camera/depth/c...
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    local_planner_node (local_planner/local_planner_node)
    tf_depth_camera (tf/static_transform_publisher)

ROS_MASTER_URI=localhost:11311

process[tf_depth_camera-1]: started with pid [14696]
process[local_planner_node-2]: started with pid [14697]
[ INFO] [1572023459.510298587]: Initializing nodelet with 4 worker threads.
[ WARN] [1572023459.876218953]: **Could not retrieve requested transform from buffer. Pointcloud dropped**
[ WARN] [1572023459.898790241]: Could not retrieve requested transform from buffer. Pointcloud dropped

 I have modified the "local_planner_aero.launch"  file in this way , changing the topic to reflect the color pointcloud of the d435 

arg name="pointcloud_topics" default="[/camera/depth/**color**/points]"

I rebuilt with many software version combinations and the result is always the same . Should be misconfiguration of mine , I use the following commands 

1) roslaunch mavros px4.launch fcu_url:=/dev/ttyUSB0:921600
2) roslaunch realsense2_camera rs_camera.launch filters:=pointcloud
3)roslaunch local_planner local_planner_aero.launch

Please help , I am struggling from weeks with this issue and I really don't know how to proceed with furher tests.
Thanks in advance !

**Comment by germal** [comment]
These are the logs from Mavros  

 roslaunch mavros px4.launch fcu_url:=/dev/ttyUSB0:92160
.

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: /dev/ttyUSB0:921600
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: odom
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: odom
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: odom
 * /mavros/wheel_odometry/tf/send: False
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [14519]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d90e8d40-f749-11e9-8aa8-d6cee9c34fd1
process[rosout-1]: started with pid [14531]
started core service [/rosout]
process[mavros-2]: started with pid [14539]
[ INFO] [1572023218.559428658]: FCU URL: /dev/ttyUSB0:921600
[ INFO] [1572023218.567919642]: serial0: device: /dev/ttyUSB0 @ 921600 bps
[ INFO] [1572023218.604219087]: GCS bridge disabled
[ INFO] [1572023218.639132154]: Plugin 3dr_radio loaded
[ INFO] [1572023218.643739423]: Plugin 3dr_radio initialized
[ INFO] [1572023218.644026876]: Plugin actuator_control loaded
[ INFO] [1572023218.651635032]: Plugin actuator_control initialized
[ INFO] [1572023218.663705715]: Plugin adsb loaded
[ INFO] [1572023218.671914141]: Plugin adsb initialized
[ INFO] [1572023218.672572799]: Plugin altitude loaded
[ INFO] [1572023218.675476496]: Plugin altitude initialized
[ INFO] [1572023218.675871347]: Plugin cam_imu_sync loaded
[ INFO] [1572023218.678037844]: Plugin cam_imu_sync initialized
[ INFO] [1572023218.678474258]: Plugin command loaded
[ INFO] [1572023218.695927484]: Plugin command initialized
[ INFO] [1572023218.696337751]: Plugin companion_process_status loaded
[ INFO] [1572023218.702326503]: Plugin companion_process_status initialized
[ INFO] [1572023218.702688697]: Plugin debug_value loaded
[ INFO] [1572023218.713877437]: Plugin debug_value initialized
[ INFO] [1572023218.714029888]: Plugin distance_sensor blacklisted
[ INFO] [1572023218.714510521]: Plugin fake_gps loaded
[ INFO] [1572023218.741166671]: Plugin fake_gps initialized
[ INFO] [1572023218.741712774]: Plugin ftp loaded
[ INFO] [1572023218.765444601]: Plugin ftp initialized
[ INFO] [1572023218.766010392]: Plugin global_position loaded
[ INFO] [1572023218.800931740]: Plugin global_position initialized
[ INFO] [1572023218.801428676]: Plugin gps_rtk loaded
[ INFO] [1572023218.807083204]: Plugin gps_rtk initialized
[ INFO] [1572023218.807516388]: Plugin hil loaded
[ INFO] [1572023218.837304520]: Plugin hil initialized
[ INFO] [1572023218.838391727]: Plugin home_position loaded
[ INFO] [1572023218.847111257]: Plugin home_position initialized
[ INFO] [1572023218.847880072]: Plugin imu loaded
[ INFO] [1572023218.864697506]: Plugin imu initialized
[ INFO] [1572023218.865108190]: Plugin landing_target loaded
[ INFO] [1572023218.896029676]: Plugin landing_target initialized
[ INFO] [1572023218.896491976]: Plugin local_position loaded
[ INFO] [1572023218.912283922]: Plugin local_position initialized
[ INFO] [1572023218.912896433]: Plugin log_transfer loaded
[ INFO] [1572023218.921215851]: Plugin log_transfer initialized
[ INFO] [1572023218.921668620]: Plugin manual_control loaded
[ INFO] [1572023218.929207920]: Plugin manual_control initialized
[ INFO] [1572023218.929625740]: Plugin mocap_pose_estimate loaded
[ INFO] [1572023218.937841250]: Plugin mocap_pose_estimate initialized
[ INFO] [1572023218.938268654]: Plugin mount_control loaded
[ INFO] [1572023218.945450760]: Plugin mount_control initialized
[ INFO] [1572023218.945842382]: Plugin obstacle_distance loaded
[ INFO] [1572023218.954172373]: Plugin obstacle_distance initialized
[ INFO] [1572023218.954563630]: Plugin odom loaded
[ INFO] [1572023218.964961158]: Plugin odom initialized
[ INFO] [1572023218.965370436]: Plugin onboard_computer_status loaded
[ INFO] [1572023218.971114913]: Plugin onboard_computer_status initialized
[ INFO] [1572023218.971691381]: Plugin param loaded
[ INFO] [1572023218.980332264]: Plugin param initialized
[ INFO] [1572023218.980763625]: Plugin px4flow loaded
[ INFO] [1572023218.996733283]: Plugin px4flow initialized
[ INFO] [1572023218.996852244]: Plugin rangefinder blacklisted
[ INFO] [1572023218.997336315]: Plugin rc_io loaded
[ INFO] [1572023219.005980010]: Plugin rc_io initialized
[ INFO] [1572023219.006108866]: Plugin safety_area blacklisted
[ INFO] [1572023219.006558405]: Plugin setpoint_accel loaded
[ INFO] [1572023219.013601864]: Plugin setpoint_accel initialized
[ INFO] [1572023219.014428232]: Plugin setpoint_attitude loaded
[ INFO] [1572023219.038096308]: Plugin setpoint_attitude initialized
[ INFO] [1572023219.038661266]: Plugin setpoint_position loaded
[ INFO] [1572023219.071925188]: Plugin setpoint_position initialized
[ INFO] [1572023219.072435093]: Plugin setpoint_raw loaded
[ INFO] [1572023219.092291018]: Plugin setpoint_raw initialized
[ INFO] [1572023219.092766130]: Plugin setpoint_velocity loaded
[ INFO] [1572023219.105369478]: Plugin setpoint_velocity initialized
[ INFO] [1572023219.106229129]: Plugin sys_status loaded
[ INFO] [1572023219.133400756]: Plugin sys_status initialized
[ INFO] [1572023219.134019673]: Plugin sys_time loaded
[ INFO] [1572023219.146689481]: TM: Timesync mode: MAVLINK
[ INFO] [1572023219.149752035]: Plugin sys_time initialized
[ INFO] [1572023219.150231002]: Plugin trajectory loaded
[ INFO] [1572023219.163595718]: Plugin trajectory initialized
[ INFO] [1572023219.164055518]: Plugin vfr_hud loaded
[ INFO] [1572023219.166122950]: Plugin vfr_hud initialized
[ INFO] [1572023219.166224046]: Plugin vibration blacklisted
[ INFO] [1572023219.166558583]: Plugin vision_pose_estimate loaded
[ INFO] [1572023219.183457580]: Plugin vision_pose_estimate initialized
[ INFO] [1572023219.183820607]: Plugin vision_speed_estimate loaded
[ INFO] [1572023219.192755714]: Plugin vision_speed_estimate initialized
[ INFO] [1572023219.193361610]: Plugin waypoint loaded
[ INFO] [1572023219.205584899]: Plugin waypoint initialized
[ INFO] [1572023219.205743808]: Plugin wheel_odometry blacklisted
[ INFO] [1572023219.206233088]: Plugin wind_estimation loaded
[ INFO] [1572023219.209199026]: Plugin wind_estimation initialized
[ INFO] [1572023219.209343351]: Autostarting mavlink via USB on PX4
[ INFO] [1572023219.209667576]: Built-in SIMD instructions: ARM NEON
[ INFO] [1572023219.209752525]: Built-in MAVLink package version: 2019.10.10
[ INFO] [1572023219.209825339]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1572023219.209967268]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1572023219.214008225]: IMU: Attitude quaternion IMU detected!
[ INFO] [1572023219.218692267]: IMU: High resolution IMU detected!
[ INFO] [1572023219.513291339]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1572023219.518579036]: IMU: High resolution IMU detected!
[ INFO] [1572023219.519635566]: IMU: Attitude quaternion IMU detected!
[ INFO] [1572023220.535565636]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1572023220.536016686]: VER: 1.1: Flight software:     010902ff (106905871d000000)
[ INFO] [1572023220.536612321]: VER: 1.1: Middleware software: 010902ff (106905871d000000)
[ INFO] [1572023220.536998422]: VER: 1.1: OS software:         071c00ff (423371c7d4012e72)
[ INFO] [1572023220.537279677]: VER: 1.1: Board hardware:      00000011
[ INFO] [1572023220.537734268]: VER: 1.1: VID/PID:             26ac:0011
[ INFO] [1572023220.538215787]: VER: 1.1: UID:                 3335510a38343732
[ WARN] [1572023220.538984030]: CMD: Unexpected command 520, result 0
[ INFO] [1572023229.517245503]: HP: requesting home position
[ INFO] [1572023234.532071685]: WP: item #0* F:3 C: 22 p: 15.000000 0.000000 0.000000 nan x: 38.740643 y: -9.302164 z: 20.000000
[ INFO] [1572023234.546613294]: WP: item #1  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 38.740627 y: -9.302159 z: 20.000000
[ INFO] [1572023234.549816996]: WP: item #2  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 38.740559 y: -9.302008 z: 20.000000
[ INFO] [1572023234.555305426]: WP: item #3  F:2 C: 20 p: 0.000000 0.000000 0.000000 nan x: 0.000000 y: -317498284827322163791582879838896128.000000 z: 20.000000
[ INFO] [1572023234.556385497]: WP: mission received
[ INFO] [1572023239.516156424]: HP: requesting home position
[ INFO] [1572023249.515614954]: HP: requesting home position
[ INFO] [1572023259.514650575]: HP: requesting home position

**Comment by JoeyLeeNPU** [comment]
I also meet the same problem, and my drone can not plan a path. So will your planner work better?

**Comment by germal** [comment]
Actually it doesn't work .The error seems to me indicating that the pointcloud coming from the Realsense camera has a format not suitable for the planner. Please help to understand .
Thanks a lot,
Germal

**Comment by jkflying** [comment]
You need PX4 Firmware 1.10 beta to use latest avoidance. This might fix your issue.

Also, I have a potential bugfix in #520 around transforming the point cloud, but this isn't your issue I think.

I'm not sure if local_planner_aero has been used in a long time...

**Comment by germal** [comment]
Hi
I tried with 1.10 beta but I found the same error.
I think too that it is an issue regarding TF transformation but in my case it is not performance related , because  the planner  doesn't work.

> . I don't think local_planner_aero has been used in a long  time...  

Do you mean that avoidance doesn't work anymore on an hardware platform ?
Thanks
Germal

**Comment by germal** [comment]
I think that this point It is worth clarifying. Do Avoidance work on an hardware platform ?
Please reply
Thanks
Germal

**Comment by jkflying** [comment]
Yes, we fly the `local_planner` regularly using both Intel and ARM companion computers.

**Comment by germal** [comment]
With a Realsense Depth camera ?

**Comment by jkflying** [comment]
Yes, and also with Structure Core.

**Comment by germal** [comment]
Could you please provide the software version combination and the steps that you have followed with Realsense ? 
I followed the readme and I have that issue on TF.
Thanks,
Germal
