### ISSUE TITLE
A target point far from the current position is set accidentally when planner running

### ISSUE THREAD

**Issue by JoeyLeeNPU** [PX4/avoidance#522]
When I set a target position using the local planner, a target point (a point between start and goal) far from the current position (red line in Rviz) will be set accidentally, then the drone rush to this point.  
Has anyone else has a similar problem? 

Thanks for help,
Joey

**Comment by mrivi** [comment]
Could you please provide more information. Can you explain exactly what you're doing?

**Comment by JoeyLeeNPU** [comment]
I set a target position far from my drone, then planner works well and my drone is flying to the target. But sometimes there exists a rush accidentally during the entire flight, I found that the (current control command is wrong) red line in rviz has a big jump. This problem happened twice, both when the drone was close to the target position.

**Comment by mrivi** [comment]
can you share the flight control log?
