### ISSUE TITLE
wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying

### ISSUE THREAD

**Issue by germal** [PX4/avoidance#525]
Avoidance : current Master
    Intel Realsense d435 camera
    Pixhawk FMUv2 with firmware 1.10
    ROS Melodic
    Mavros master -> 0.33.0
    Mavlink 2019.10.10

**The error triggers after
roslaunch local_planner avoidance.launch**

please find attached the avoidance.launch which I use
[avoidance.txt](https://github.com/PX4/avoidance/files/3832309/avoidance.txt)
please advice ,
Thanks

mluser@jetson:~$ roslaunch local_planner avoidance.launch 
... logging to /home/mluser/.ros/log/23374ea8-04a0-11ea-86ee-d6cee9c34fd1/roslaunch-jetson-6904.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server 192.168.1.1:34403/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 0
 * /camera/realsense2_camera/accel_frame_id: _accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: _accel_optical_frame
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: _aligned_depth_to...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: _aligned_depth_to...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: _aligned_depth_to...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: _aligned_depth_to...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: _aligned_depth_to...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: _aligned_depth_to...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: _link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: _color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: _color_optical_frame
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: _depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: _depth_optical_frame
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_pointcloud: True
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: _fisheye1_frame
 * /camera/realsense2_camera/fisheye1_optical_frame_id: _fisheye1_optical...
 * /camera/realsense2_camera/fisheye2_frame_id: _fisheye2_frame
 * /camera/realsense2_camera/fisheye2_optical_frame_id: _fisheye2_optical...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: _fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 0
 * /camera/realsense2_camera/fisheye_optical_frame_id: _fisheye_optical_...
 * /camera/realsense2_camera/fisheye_width: 0
 * /camera/realsense2_camera/gyro_fps: 0
 * /camera/realsense2_camera/gyro_frame_id: _gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: _gyro_optical_frame
 * /camera/realsense2_camera/imu_optical_frame_id: _imu_optical_frame
 * /camera/realsense2_camera/infra1_frame_id: _infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: _infra1_optical_f...
 * /camera/realsense2_camera/infra2_frame_id: _infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: _infra2_optical_f...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: /home/mluser/catk...
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: _odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: _pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: _pose_optical_frame
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 832112070319
 * /camera/realsense2_camera/topic_odom_in: /odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /local_planner_node/goal_x_param: 0
 * /local_planner_node/goal_y_param: 0
 * /local_planner_node/goal_z_param: 4
 * /local_planner_node/pointcloud_topics: ['/camera/depth/p...
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    points_xyz_sw_registered (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    drop_camera_depth (topic_tools/drop)
    drop_camera_ir (topic_tools/drop)
    dynparam (dynamic_reconfigure/dynparam)
    local_planner_node (local_planner/local_planner_node)
    rqt_param_toggle (local_planner/rqt_param_toggle.sh)
    tf_camera (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[tf_camera-1]: started with pid [6919]
process[camera/realsense2_camera_manager-2]: started with pid [6920]
process[camera/realsense2_camera-3]: started with pid [6923]
process[camera/points_xyz_sw_registered-4]: started with pid [6927]
process[drop_camera_depth-5]: started with pid [6929]
process[drop_camera_ir-6]: started with pid [6934]
process[dynparam-7]: started with pid [6945]
process[local_planner_node-8]: started with pid [6950]
process[rqt_param_toggle-9]: started with pid [6952]
[ INFO] [1573489810.810440525]: Initializing nodelet with 4 worker threads.
[ INFO] [1573489810.966181853]: Initializing nodelet with 4 worker threads.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Duration is out of dual 32-bit range
[ INFO] [1573489812.358042866]: RealSense ROS v2.2.7
[ INFO] [1573489812.358784351]: Running with LibRealSense v2.24.0
[local_planner_node-8] process has died [pid 6950, exit code -6, cmd /home/mluser/catkin_ws/devel/lib/local_planner/local_planner_node __name:=local_planner_node __log:=/home/mluser/.ros/log/23374ea8-04a0-11ea-86ee-d6cee9c34fd1/local_planner_node-8.log].
log file: /home/mluser/.ros/log/23374ea8-04a0-11ea-86ee-d6cee9c34fd1/local_planner_node-8*.log
[ INFO] [1573489812.826217735]: getParameters...
[ INFO] [1573489812.968896527]: setupDevice...
[ INFO] [1573489813.324054730]: JSON file is loaded! (/home/mluser/catkin_ws/src/avoidance/local_planner/resource/stereo_calib.json)
[ INFO] [1573489813.324403834]: ROS Node Namespace: camera
[ INFO] [1573489813.324474352]: Device Name: Intel RealSense D435
[ INFO] [1573489813.324865069]: Device Serial No: 832112070319
[ INFO] [1573489813.324967462]: Device FW version: 05.09.13.00
[ INFO] [1573489813.325085114]: Device Product ID: 0x0B07
[ INFO] [1573489813.325147716]: Enable PointCloud: On
[ INFO] [1573489813.325207298]: Align Depth: Off
[ INFO] [1573489813.325340939]: Sync Mode: On
[ INFO] [1573489813.326531110]: Device Sensors: 
[ INFO] [1573489813.328051010]: Stereo Module was found.
[ INFO] [1573489813.328947648]: RGB Camera was found.
[ INFO] [1573489813.329817256]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1573489813.330021573]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1573489813.330310574]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1573489813.330512912]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1573489813.330599159]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1573489813.330739363]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1573489813.331127423]: Setting Dynamic reconfig parameters.
[ INFO] [1573489813.465605733]: Done Setting Dynamic reconfig parameters.
[ INFO] [1573489813.546381830]: depth stream is enabled - width: 640, height: 480, fps: 30
[ WARN] [1573489813.546722809]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 1, Width: 640, Height: 480, FPS: 15
[ INFO] [1573489813.549236948]: color stream is enabled - width: 640, height: 480, fps: 15
[ INFO] [1573489813.549490274]: setupPublishers...
[ INFO] [1573489813.558930080]: Expected frequency for depth = 30.00000
[ INFO] [1573489813.664064732]: Expected frequency for color = 15.00000
[ INFO] [1573489813.718048758]: setupStreams...
[ INFO] [1573489813.722377163]: insert Depth to Stereo Module
[ INFO] [1573489813.723047298]: insert Color to RGB Camera
[ INFO] [1573489813.959271772]: Add Filter: pointcloud
[ INFO] [1573489813.961682321]: num_filters: 1
[ INFO] [1573489813.961842368]: SELECTED BASE:Depth, 0
[ INFO] [1573489813.964078599]: RealSense Node Is Up!
 11/11 11:30:14,010 WARNING [546786234752] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to the installation chapter for details.
 11/11 11:30:14,111 WARNING [546534584704] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to the installation chapter for details.
[ WARN] [1573489814.114193771]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
advertised as /camera/depth/image_rect_raw_drop
[WARN] [1573489814.656207]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying
Waiting for service /local_planner_node/set_parameters...
[WARN] [1573489815.875606]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying
[rqt_param_toggle-9] process has finished cleanly
log file: /home/mluser/.ros/log/23374ea8-04a0-11ea-86ee-d6cee9c34fd1/rqt_param_toggle-9*.log
[WARN] [1573489825.896404]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying
[WARN] [1573489835.924538]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying
[WARN] [1573489845.946596]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying
[WARN] [1573489855.972493]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying
[WARN] [1573489866.002758]: wait_for_service(/local_planner_node/set_parameters): failed to contact, will keep trying

**Comment by mrivi** [comment]
it means that the parameters are under a different namespace and the service your are calling to set them in the launch file cannot find them. Once you have launch the planner you can run`rosparam list` to check under which namespace the parameter you are trying to change are.

**Comment by germal** [comment]
Thanks @mrivi , I rebuilt my avoidance.launch with the generation script provided , correcting also the   px4_config.yaml path ,  as you adviced  at #523 

> Please use the px4_config.yaml inside ~/catkin_ws/src/avoidance/avoidance/resource > 

and now the local planner starts without issues
Thanks a lot !
Germal

**Comment by kal1b** [comment]
> Thanks @mrivi , I rebuilt my avoidance.launch with the generation script provided , correcting also the px4_config.yaml path , as you adviced at #523
> 
> > Please use the px4_config.yaml inside ~/catkin_ws/src/avoidance/avoidance/resource >
> 
> and now the local planner starts without issues
> Thanks a lot !
> Germal

HOW it work?( What commands should be used to solve the problem? I just can't understand, I'm just getting used to it.
