### ISSUE TITLE
local_planner_node 

### ISSUE THREAD

**Issue by woongjoonchoi** [PX4/avoidance#532]
**Describe the bug**
when i run local_planner_realsense.launch , local_planner_node being created
But,  local_planner_node published nothing.!!

**To Reproduce**
1. Drone switched on '...'
2. Uploaded mission '....' (attach QGC mission file)
3. Took off '....'

**Expected behavior**

**Log Files and Screenshots**
*Always* provide a link to the flight log file:
- Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)) or from the Gazebo simulation (logs are located in `~/.ros/logs/`)
- Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).
- Share a link to a rosbag showing the problem

-VivoBook-ASUSLaptop-X512DA-R564DA:~$ rostopic echo /world
WARNING: no messages received and simulated time is active.
Is /clock being published?
VivoBook-ASUSLaptop-X512DA-R564DA:~$ rostopic echo /fov
WARNING: no messages received and simulated time is active.
Is /clock being published?
-VivoBook-ASUSLaptop-X512DA-R564DA:~$ rostopic echo /local_pointcloud
WARNING: no messages received and simulated time is active.
Is /clock being published?
itis some of topic that local_planner_node publishes.
**Additional context**/clicked_point

**Comment by mrivi** [comment]
Hi, `local_planner_realsense.launch` hasn't been updated and it isn't compatible with the current codebase. I am sorry about that. I am going to deprecate it.
Please use `local_planner_depth-camera.launch`. Thank you
