### ISSUE TITLE
HP: requesting home_position

### ISSUE THREAD

**Issue by QING-ML** [PX4/avoidance#537]
When I directly use model in folder avoidance. mavros requesting home_position. How do you set home_position in local planner.
Thanks

**Comment by mrivi** [comment]
The home position is set by the flight controller. How are you launch the local planner?

**Comment by QING-ML** [comment]
launch the local planner is right. I can get the home_position. But when i only use the models in package avoidance and mavros. There are no msgs from topic /mavros/home_position/home.
so I can't active the rotor and launch myself motion planner.

**Comment by mrivi** [comment]
The models don't have any capabilities by themself. You need to launch the autopilot to do anything with them. See the documentation here https://dev.px4.io/v1.9.0/en/simulation/ros_interface.html#launching-rossimulation
