### ISSUE TITLE
TM : Time jump detected. Resetting time synchroniser

### ISSUE THREAD

**Issue by maerad7** [PX4/avoidance#538]
Not arming.

help me.

[ INFO] [1574997405.540789888]: ROS Node Namespace: camera
[ INFO] [1574997405.540842432]: Device Name: Intel RealSense D435
[ INFO] [1574997405.540879648]: Device Serial No: 825312070955
[ INFO] [1574997405.540912768]: Device FW version: 05.11.15.00
[ INFO] [1574997405.540951744]: Device Product ID: 0x0B07
[ INFO] [1574997405.540984352]: Enable PointCloud: Off
[ INFO] [1574997405.541014208]: Align Depth: Off
[ INFO] [1574997405.541043712]: Sync Mode: Off
[ INFO] [1574997405.541722816]: Device Sensors: 
[ INFO] [1574997405.542272320]: Stereo Module was found.
[ INFO] [1574997405.542414400]: RGB Camera was found.
[ INFO] [1574997405.542524896]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1574997405.542576768]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1574997405.542610496]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1574997405.542650848]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1574997405.542686912]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1574997405.542722624]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1574997405.543278752]: num_filters: 0
[ INFO] [1574997405.543329088]: Setting Dynamic reconfig parameters.
[ INFO] [1574997405.568222496]: Plugin setpoint_velocity initialized
[ INFO] [1574997405.568655520]: Plugin sys_status loaded
[ INFO] [1574997405.605556256]: Plugin sys_status initialized
[ INFO] [1574997405.605923168]: Plugin sys_time loaded
[ INFO] [1574997405.626567168]: TM: Timesync mode: MAVLINK
[ INFO] [1574997405.631787904]: Plugin sys_time initialized
[ INFO] [1574997405.632254080]: Plugin trajectory loaded
[ INFO] [1574997405.688458528]: Plugin trajectory initialized
[ INFO] [1574997405.688884640]: Plugin vfr_hud loaded
[ INFO] [1574997405.691370880]: Plugin vfr_hud initialized
[ INFO] [1574997405.691481248]: Plugin vibration blacklisted
[ INFO] [1574997405.691761536]: Plugin vision_pose_estimate loaded
[ INFO] [1574997405.755335680]: Plugin vision_pose_estimate initialized
[ INFO] [1574997405.755882496]: Plugin vision_speed_estimate loaded
[ INFO] [1574997405.804118336]: Plugin vision_speed_estimate initialized
[ INFO] [1574997405.804876544]: Plugin waypoint loaded
[ INFO] [1574997405.867279584]: Plugin waypoint initialized
[ INFO] [1574997405.867478144]: Plugin wheel_odometry blacklisted
[ INFO] [1574997405.868134272]: Plugin wind_estimation loaded
[ INFO] [1574997405.875830272]: Plugin wind_estimation initialized
[ INFO] [1574997405.876114464]: Autostarting mavlink via USB on PX4
[ INFO] [1574997405.876322592]: Built-in SIMD instructions: ARM NEON
[ INFO] [1574997405.876447456]: Built-in MAVLink package version: 2019.11.11
[ INFO] [1574997405.876581600]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1574997405.876699296]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1574997405.884652416]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ERROR] [1574997405.892702368]: FCU: REJECT POSITION CONTROL
[ INFO] [1574997405.893391360]: IMU: Attitude quaternion IMU detected!
[ INFO] [1574997405.893660480]: IMU: High resolution IMU detected!
[ INFO] [1574997405.894097184]: RC_CHANNELS message detected!
[ INFO] [1574997405.938179904]: Done Setting Dynamic reconfig parameters.
[ERROR] [1574997405.942341152]: FCU: REJECT POSITION CONTROL
[ERROR] [1574997405.988139488]: FCU: No range data received, no movement allowed.
[ERROR] [1574997406.036890464]: FCU: No range data received, no movement allowed.
[ERROR] [1574997406.085796000]: FCU: No range data received, no movement allowed.
[ INFO] [1574997406.893116928]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1574997406.893254912]: VER: 1.1: Flight software:     010a0080 (4964b633b2000000)
[ INFO] [1574997406.893328064]: VER: 1.1: Middleware software: 010a0080 (4964b633b2000000)
[ INFO] [1574997406.893387488]: VER: 1.1: OS software:         00000000 (66401c8960c5211d)
[ INFO] [1574997406.893438368]: VER: 1.1: Board hardware:      00000011
[ INFO] [1574997406.893484256]: VER: 1.1: VID/PID:             26ac:0011
[ INFO] [1574997406.893528160]: VER: 1.1: UID:                 3337510d37353832
[ WARN] [1574997406.895116928]: CMD: Unexpected command 520, result 0
[ INFO] [1574997406.926283456]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1574997406.927018656]: infra1 stream is enabled - width: 640, height: 480, fps: 15
[ INFO] [1574997406.927158048]: setupPublishers...
[ INFO] [1574997406.936333440]: Expected frequency for depth = 30.00000
[ INFO] [1574997407.050882336]: Expected frequency for infra1 = 15.00000
[ INFO] [1574997407.147910368]: setupStreams...
[ INFO] [1574997407.150737856]: insert Depth to Stereo Module
[ INFO] [1574997407.151346880]: insert Infrared to Stereo Module
[ WARN] [1574997408.930165504]: TM : RTT too high for timesync: 197.97 ms.
[ INFO] [1574997409.525994016]: SELECTED BASE:Depth, 0
[ INFO] [1574997409.549156320]: RealSense Node Is Up!
[rqt_param_toggle-10] process has finished cleanly
log file: /home/nvidia/.ros/log/a9aadf7c-1256-11ea-8b26-0a3d1e2251ab/rqt_param_toggle-10*.log
 29/11 12:16:49,678 WARNING [547591549328] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to the installation chapter for details.
[ WARN] [1574997409.679863264]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
advertised as /camera/infra1/image_rect_raw_drop
[ERROR] [1574997409.698811936]: PR: Unknown parameter to get: MPC_ACC_HOR
advertised as /camera/depth/image_rect_raw_drop
[ERROR] [1574997409.707278912]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1574997409.712034368]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1574997409.721919584]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1574997409.727421184]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1574997409.733096608]: PR: Unknown parameter to get: NAV_ACC_RAD
[ERROR] [1574997409.742156192]: TF Buffer: could not retrieve requested transform from buffer, unregistered
[ WARN] [1574997409.743850944]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.753525696]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.758083488]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.762887200]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.768072608]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.773237536]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.778476224]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.783687424]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.788846304]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.794027104]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.799349952]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.804591456]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.809848800]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.815533312]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.820892416]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.826158176]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.831609632]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.836824704]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.842123328]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.847399680]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.852607072]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.857797824]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.862974464]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.868215648]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.873470496]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.880731424]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.886052032]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.891455840]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.896808256]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.902244832]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.907524736]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.912770080]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.917963776]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.923219136]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.928493056]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.933763616]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.939485536]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.949717120]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.953996128]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.959295872]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.964591296]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.969929088]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.975166400]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.980501408]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.985771296]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.991030176]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997409.996214240]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.001447456]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.006648128]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.011820576]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.017480288]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.022556416]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.028352896]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.034763488]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ WARN] [1574997410.038730720]: TF Buffer: could not retrieve requested transform from buffer, tf has already been dropped from buffer
[ERROR] [1574997414.737880768]: PR: Unknown parameter to get: MPC_ACC_HOR
[ERROR] [1574997414.742594176]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1574997414.747178816]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1574997414.758695264]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1574997414.771739680]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1574997414.780331776]: PR: Unknown parameter to get: NAV_ACC_RAD
[ INFO] [1574997416.745361216]: parameter CP_DIST is set from  nan to 7.000000 

[ INFO] [1574997417.903308128]: parameter MPC_ACC_HOR is set from  nan to 3.000000 

[ INFO] [1574997417.906726400]: parameter MPC_ACC_UP_MAX is set from  nan to 4.000000 

[ INFO] [1574997417.916186400]: parameter MPC_AUTO_MODE is set from -1 to 1 

[ INFO] [1574997417.948237888]: parameter MPC_JERK_MAX is set from  nan to 20.000000 

[ INFO] [1574997417.978534912]: parameter MPC_LAND_SPEED is set from  nan to 0.700000 

[ INFO] [1574997418.059428000]: parameter MPC_TKO_SPEED is set from  nan to 1.500000 

[ INFO] [1574997418.076909376]: parameter MPC_XY_CRUISE is set from  nan to 5.000000 

[ INFO] [1574997418.170043008]: parameter MPC_Z_VEL_MAX_UP is set from  nan to 3.000000 

[ INFO] [1574997418.179223136]: parameter NAV_ACC_RAD is set from  nan to 2.000000 

[ INFO] [1574997420.896251840]: WP: mission received
 29/11 12:20:39,591 ERROR [547583160720] (ds5-options.cpp:82) Asic Temperature value is not valid!
[ WARN] [1574997639.856628544]: GP: No GPS fix
[ERROR] [1574997657.437591255]: TM : Time jump detected. Resetting time synchroniser.
[ WARN] [1574997670.626892193]: GP: No GPS fix
[ WARN] [1574997700.638812984]: GP: No GPS fix
[ERROR] [1574997711.437008914]: TM : Time jump detected. Resetting time synchroniser.

**Comment by baumanta** [comment]
This is not very helpful. Please provide more information about where you are running and what is happening. Is this SITL or on a board? If so, which board. Also I see: [ INFO] [1574997405.540984352]: Enable PointCloud: Off
So does the camera publish a pointcloud? If it is not arming, what message do you get?

**Comment by maerad7** [comment]
Sorry
Information 
jetson Tx2 + j120 board
Intel d435 camera
os ubuntu 16.04
px4 avoidance version -> master
realsense sdk version( jetsonhacks install version )v2.13.0
reasense-ros wrapper 2.2.8

OK point cloud off....

I will solve the problem, but I hope you can let me know if there is a way.

**Comment by baumanta** [comment]
you probably need to change some parameter in the realsense launch file. You can verify if the pointcloud is really published by `rostopic hz /pointcloud_topic_name`

**Comment by maerad7** [comment]
Thank you very much. I'll try it in two days.

**Comment by maerad7** [comment]
I solved it by restarting.
thanks

**Comment by IngTIKNA** [comment]
The same error occurs when PX4(already armed) is connected to the QGroundControl

**Comment by BEI11HAI** [comment]
@IngTIKNA Did you solve the issue? I'm in the same situation as well
