### ISSUE TITLE
Failed to start local planner, Local planner hangs at "Planner abort: missing required data ".

### ISSUE THREAD

**Issue by shrazshad** [PX4/avoidance#539]
cribe the bug**
1. Local planner hangs at "Planner abort: missing required data ".
2. ![rosgraph](https://user-images.githubusercontent.com/58456016/70020785-11d4f400-15c9-11ea-80ff-52eb6e4c1108.png)
3. rostopic list | grep points shows nothing related to depth camera, i think depth camera somehow failed to be turned on?

**To Reproduce**
1. using either px4 1.9.2 or master has the same result.
2. using : roslaunch local_planner local_planner_depth-camera.launch

**Expected behavior**
Planner should be ready to be switched to offboard mode and fly

**Log Files and Screenshots**
*Always* provide a link to the flight log file:

`SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /local_planner_nodelet/goal_x_param: 17
 * /local_planner_nodelet/goal_y_param: 15
 * /local_planner_nodelet/goal_z_param: 3
 * /local_planner_nodelet/pointcloud_topics: ['/camera/depth/p...
 * /local_planner_nodelet/world_name: /home/shr/softwar...
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: local_origin
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: False
 * /mavros/mocap/use_tf: True
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    local_planner_manager (nodelet/nodelet)
    local_planner_nodelet (nodelet/nodelet)
    mavros (mavros/mavros_node)
    rqt_reconfigure (rqt_reconfigure/rqt_reconfigure)
    rviz (rviz/rviz)
    sitl_0 (px4/px4)
    spawn_model (gazebo_ros/spawn_model)
    tf_depth_camera (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [19187]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 262fb04c-1584-11ea-8ecb-488ad258d3b0
process[rosout-1]: started with pid [19204]
started core service [/rosout]
process[tf_depth_camera-2]: started with pid [19229]
process[rqt_reconfigure-3]: started with pid [19230]
process[sitl_0-4]: started with pid [19250]
INFO  [px4] Creating symlink /home/shr/software/px4-1.9.2/Firmware/ROMFS/px4fmu_common -> /home/shr/.ros/etc
0 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
process[mavros-5]: started with pid [19266]
process[gazebo-6]: started with pid [19272]
process[spawn_model-7]: started with pid [19287]
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
process[local_planner_manager-8]: started with pid [19305]
process[local_planner_nodelet-9]: started with pid [19315]
INFO  [simulator] Waiting for simulator to connect on TCP port 4560
process[rviz-10]: started with pid [19318]
[ INFO] [1575346791.732889406]: Initializing nodelet with 6 worker threads.
[ INFO] [1575346791.736177018]: Loading nodelet /local_planner_nodelet of type LocalPlannerNodelet to manager local_planner_manager with the following remappings:
[ INFO] [1575346791.777170510]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1575346791.778275951]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1575346791.778339792]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1575346791.778409999]: GCS bridge disabled
[ INFO] [1575346791.798971040]: Plugin 3dr_radio loaded
[ INFO] [1575346791.809936249]: Plugin 3dr_radio initialized
[ INFO] [1575346791.810022945]: Plugin actuator_control loaded
[ INFO] [1575346791.813538338]: rviz version 1.12.17
[ INFO] [1575346791.813568344]: compiled against Qt version 5.5.1
[ INFO] [1575346791.813575836]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1575346791.814192852]: Plugin actuator_control initialized
[ INFO] [1575346791.816283061]: Plugin adsb loaded
[ INFO] [1575346791.822690402]: Plugin adsb initialized
[ INFO] [1575346791.822781128]: Plugin altitude loaded
[ INFO] [1575346791.824562217]: Plugin altitude initialized
[ INFO] [1575346791.824624102]: Plugin cam_imu_sync loaded
[ INFO] [1575346791.825556259]: Plugin cam_imu_sync initialized
[ INFO] [1575346791.825622383]: Plugin command loaded
[ INFO] [1575346791.852250204]: Plugin command initialized
[ INFO] [1575346791.852325593]: Plugin companion_process_status loaded
[ INFO] [1575346791.856977729]: Plugin companion_process_status initialized
[ INFO] [1575346791.857048542]: Plugin debug_value loaded
[ INFO] [1575346791.868482930]: Plugin debug_value initialized
[ INFO] [1575346791.868534961]: Plugin distance_sensor blacklisted
[ INFO] [1575346791.868621459]: Plugin fake_gps loaded
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
[ INFO] [1575346791.886801082]: Plugin fake_gps initialized
[ INFO] [1575346791.886919968]: Plugin ftp loaded
[ INFO] [1575346791.894857569]: Plugin ftp initialized
[ INFO] [1575346791.894948171]: Plugin global_position loaded
[ INFO] [1575346791.931881895]: Plugin global_position initialized
[ INFO] [1575346791.932016004]: Plugin gps_rtk loaded
[ INFO] [1575346791.933917931]: Plugin gps_rtk initialized
[ INFO] [1575346791.933993926]: Plugin hil loaded
[ INFO] [1575346791.943686348]: Plugin hil initialized
[ INFO] [1575346791.943775317]: Plugin home_position loaded
[ INFO] [1575346791.946915899]: Plugin home_position initialized
[ INFO] [1575346791.947000022]: Plugin imu loaded
[ INFO] [1575346791.952176552]: Plugin imu initialized
[ INFO] [1575346791.952265306]: Plugin landing_target loaded
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
[ INFO] [1575346791.964627882]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1575346791.965318732]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1575346791.965645380]: Plugin landing_target initialized
[ INFO] [1575346791.965725748]: Plugin local_position loaded
[ INFO] [1575346791.970455663]: Plugin local_position initialized
[ INFO] [1575346791.970544120]: Plugin log_transfer loaded
[ INFO] [1575346791.972309314]: Plugin log_transfer initialized
[ INFO] [1575346791.972397923]: Plugin manual_control loaded
[ INFO] [1575346791.974856518]: Plugin manual_control initialized
[ INFO] [1575346791.974976210]: Plugin mocap_pose_estimate loaded
[ INFO] [1575346791.977805097]: Plugin mocap_pose_estimate initialized
[ INFO] [1575346791.977903222]: Plugin mount_control loaded
[ INFO] [1575346791.980355283]: Plugin mount_control initialized
[ INFO] [1575346791.980440041]: Plugin obstacle_distance loaded
[ INFO] [1575346791.982460727]: Plugin obstacle_distance initialized
[ INFO] [1575346791.982554302]: Plugin odom loaded
[ INFO] [1575346791.986367607]: Plugin odom initialized
[ INFO] [1575346791.986437426]: Plugin onboard_computer_status loaded
SpawnModel script started
[ INFO] [1575346791.988342027]: Plugin onboard_computer_status initialized
[ INFO] [1575346791.988420427]: Plugin param loaded
[ INFO] [1575346791.990277787]: Plugin param initialized
[ INFO] [1575346791.990356175]: Plugin px4flow loaded
[ INFO] [1575346791.998043246]: Plugin px4flow initialized
[ INFO] [1575346791.998064466]: Plugin rangefinder blacklisted
[ INFO] [1575346791.998138374]: Plugin rc_io loaded
[ INFO] [1575346792.001920206]: Plugin rc_io initialized
[ INFO] [1575346792.001940558]: Plugin safety_area blacklisted
[ INFO] [1575346792.002012755]: Plugin setpoint_accel loaded
[ INFO] [1575346792.004159305]: Plugin setpoint_accel initialized
[ INFO] [1575346792.004260088]: Plugin setpoint_attitude loaded
[ INFO] [1575346792.013065164]: Plugin setpoint_attitude initialized
[ INFO] [1575346792.013192714]: Plugin setpoint_position loaded
[ INFO] [1575346792.024556028]: Plugin setpoint_position initialized
[ INFO] [1575346792.024658225]: Plugin setpoint_raw loaded
[ INFO] [1575346792.030503959]: Plugin setpoint_raw initialized
[ INFO] [1575346792.030651621]: Plugin setpoint_trajectory loaded
[ INFO] [1575346792.033947111]: Plugin setpoint_trajectory initialized
[ INFO] [1575346792.034060404]: Plugin setpoint_velocity loaded
[ INFO] [1575346792.038563981]: Plugin setpoint_velocity initialized
[ INFO] [1575346792.038678744]: Plugin sys_status loaded
[ INFO] [1575346792.047685146]: Plugin sys_status initialized
[ INFO] [1575346792.047791976]: Plugin sys_time loaded
[ INFO] [1575346792.052115023]: TM: Timesync mode: MAVLINK
[ INFO] [1575346792.052989552]: Plugin sys_time initialized
[ INFO] [1575346792.053062626]: Plugin trajectory loaded
[ INFO] [1575346792.056788630]: Plugin trajectory initialized
[ INFO] [1575346792.056870819]: Plugin vfr_hud loaded
[ INFO] [1575346792.057498995]: Plugin vfr_hud initialized
[ INFO] [1575346792.057516132]: Plugin vibration blacklisted
[ INFO] [1575346792.057578619]: Plugin vision_pose_estimate loaded
[ INFO] [1575346792.062856983]: Plugin vision_pose_estimate initialized
[ INFO] [1575346792.062924360]: Plugin vision_speed_estimate loaded
[ INFO] [1575346792.065298179]: Plugin vision_speed_estimate initialized
[ INFO] [1575346792.065374621]: Plugin waypoint loaded
[ INFO] [1575346792.068393474]: Plugin waypoint initialized
[ INFO] [1575346792.068412188]: Plugin wheel_odometry blacklisted
[ INFO] [1575346792.068479544]: Plugin wind_estimation loaded
[ INFO] [1575346792.068892693]: Plugin wind_estimation initialized
[ INFO] [1575346792.068913676]: Autostarting mavlink via USB on PX4
[ INFO] [1575346792.068934303]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1575346792.068946871]: Built-in MAVLink package version: 2019.11.11
[ INFO] [1575346792.068962491]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1575346792.068975195]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[INFO] [1575346792.118905, 0.000000]: Loading model XML from Gazebo Model Database
[INFO] [1575346792.119073, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ INFO] [1575346793.150577031]: Stereo is NOT SUPPORTED
[ INFO] [1575346793.150648094]: OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [1575346793.593460742, 0.024000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1575346793.628172, 0.000000]: Calling service /gazebo/spawn_sdf_model
[INFO] [1575346793.831689, 0.136000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1575346793.839101857, 0.136000000]: Physics dynamic reconfigure ready.
[spawn_model-7] process has finished cleanly
log file: /home/shr/.ros/log/262fb04c-1584-11ea-8ecb-488ad258d3b0/spawn_model-7*.log
INFO  [simulator] Simulator connected on TCP port 4560.
INFO  [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14570 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14558 remote port 14541
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log (type: full)
INFO  [logger] Opened full log file: ./log/2019-12-03/04_19_55.ulg
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [px4] Startup script returned successfully
[ INFO] [1575346795.885942315, 1.284000000]: udp0: Remote address: 127.0.0.1:14580
[ INFO] [1575346795.886003950, 1.284000000]: IMU: High resolution IMU detected!
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1575346796.169937731, 1.568000000]: FCU: [logger] file: ./log/2019-12-03/04_19_55.ulg
[ INFO] [1575346796.221763274, 1.620000000]: FCU: Avoidance system starting
[ INFO] [1575346796.603823956, 2.000000000]: Successfully loaded rviz world
[ERROR] [1575346796.853663750, 2.248000000]: PR: Unknown parameter to get: MPC_ACC_HOR
[ERROR] [1575346796.854343929, 2.252000000]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1575346796.854926193, 2.252000000]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1575346796.855433894, 2.252000000]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1575346796.855944436, 2.252000000]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1575346796.856496544, 2.252000000]: PR: Unknown parameter to get: NAV_ACC_RAD
[ INFO] [1575346796.866198204, 2.264000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1575346796.886117026, 2.284000000]: IMU: High resolution IMU detected!
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1575346797.081410414, 2.476000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1575346797.215559707, 2.612000000]: FCU: Avoidance system connected
[ INFO] [1575346797.868025512, 3.264000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1575346797.868055894, 3.264000000]: VER: 1.1: Flight software:     010902ff (106905871d000000)
[ INFO] [1575346797.868071818, 3.264000000]: VER: 1.1: Middleware software: 010902ff (106905871d000000)
[ INFO] [1575346797.868084686, 3.264000000]: VER: 1.1: OS software:         040f00ff (423371c7d4012e72)
[ INFO] [1575346797.868096969, 3.264000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1575346797.868107869, 3.264000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1575346797.868117809, 3.264000000]: VER: 1.1: UID:                 4954414c44494e4f
[ INFO] [1575346799.824749810, 5.216000000]: FCU: Avoidance system timed out
[ERROR] [1575346801.858814839, 7.244000000]: PR: Unknown parameter to get: MPC_ACC_HOR
[ERROR] [1575346801.860952803, 7.248000000]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1575346801.863100720, 7.248000000]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1575346801.865417884, 7.252000000]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1575346801.867683891, 7.256000000]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1575346801.869726937, 7.256000000]: PR: Unknown parameter to get: NAV_ACC_RAD
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ERROR] [1575346806.873196454, 12.156000000]: PR: Unknown parameter to get: MPC_ACC_HOR
[ERROR] [1575346806.876273450, 12.160000000]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1575346806.879366396, 12.164000000]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1575346806.882347549, 12.164000000]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1575346806.885852596, 12.168000000]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1575346806.889625519, 12.172000000]: PR: Unknown parameter to get: NAV_ACC_RAD
[ INFO] [1575346806.979652240, 12.264000000]: HP: requesting home position
[ INFO] [1575346807.237011311, 12.520000000]: parameter MPC_JERK_MAX is set from  nan to 20.000000 

[ INFO] [1575346807.237594580, 12.520000000]: parameter MPC_LAND_SPEED is set from  nan to 0.700000 

[ INFO] [1575346807.257651306, 12.540000000]: parameter MPC_XY_CRUISE is set from  nan to 5.000000 

[ INFO] [1575346807.278275012, 12.560000000]: parameter MPC_Z_VEL_MAX_DN is set from  nan to 1.000000 

[ WARN] [1575346808.437909218, 13.720000000]: PR: request param #139 timeout, retries left 2, and 1 params still missing
[ WARN] [1575346808.438429782, 13.720000000]: PR: Param EKF2_EV_DELAY (138/563): <value><double>175</double></value> different index: 139/564
since_last_cloud: 15.084
[ WARN] [1575346809.803272376, 15.084000000]:  Planner abort: missing required data 
 
since_last_cloud: 15.184
[ WARN] [1575346809.903234310, 15.184000000]:  Planner abort: missing required data 
 
WARN  [commander] Avoidance system rejected
[ERROR] [1575346809.935751947, 15.216000000]: FCU: Avoidance system rejected
since_last_cloud: 15.284
[ WARN] [1575346810.004116297, 15.284000000]:  Planner abort: missing required data 
 
since_last_cloud: 15.384
[ WARN] [1575346810.104153280, 15.384000000]:  Planner abort: missing required data 
 
since_last_cloud: 15.484
[ WARN] [1575346810.203717628, 15.484000000]:  Planner abort: missing required data 
 
since_last_cloud: 15.584
[ WARN] [1575346810.304611837, 15.584000000]:  Planner abort: missing required data 
 
since_last_cloud: 15.684
[ WARN] [1575346810.403636776, 15.684000000]:  Planner abort: missing required data 
 
since_last_cloud: 15.784
[ WARN] [1575346810.504258717, 15.784000000]:  Planner abort: missing required data 
 
^Csince_last_cloud: 15.884
[ WARN] [1575346810.603954975, 15.884000000]:  Planner abort: missing required data`

**Additional context**

**Comment by mrivi** [comment]
Can you see the vehicle and the world visualization in rviz? Could you please share the output of `echo $GAZEBO_MODEL_PATH` and `echo $GAZEBO_PLUGIN_PATH` here?

**Comment by khbnzr** [comment]
@mrivi My issue is similar. The output of - 
echo $GAZEBO_PLUGIN_PATH - /usr/lib/x86_64-linux-gnu/gazebo-7/plugins:
echo $GAZEBO_MODEL_PATH - have both /avoidance/avoidance/sim/worlds & /avoidance/avoidance/sim/models.

What could be the possible reason for the above logs by @shrazshad. Thanks in advance.

**Comment by baumanta** [comment]
The planner basically needs to things in order to work:
- information from the flight controller (/mavros/local_position/pose, ...)
- pointcloud

Try to do rostopic list and then look at the rates at which you are getting this information. If either of them is not published or way too slow you will see the mentioned warnings. If the pointcloud is missing, you might have problems with the gazebo plugin or model of the camera/drone. If the stuff from mavros is missing, you might have wrong fcu url or did not build the firmware correctly.

**Comment by khbnzr** [comment]
@baumanta I am getting the data on /mavros/local_position/pose topic but not on pointcloud. I've installed the gazebo using apt ros-kinetic-gazebo-* , which installs gazebo-7. I'm using this drone/camera model from the launch file - https://github.com/PX4/avoidance/blob/master/avoidance/launch/avoidance_sitl_mavros.launch#L41-L44. I've uninstalled and re-installed the gazebo-7 but the issue was same. Am i missing something here ?

**Comment by PonyZhou** [comment]
I had the same issue when launching local_planner_realsense.launch. And i found the pointclod is not published. Since the realsense camera can publish /depth/points topic directly, i wonder whether PX4/disparity_to_point_cloud is necessary.

**Comment by nicovanduijn** [comment]
Note that the `local_planner_realsense.launch` is a launchfile to run using actual hardware, while @khbnzr seems to be working in simulation.

@PonyZhou We experimented with both the pointcloud generated by the device directly, as well as the point cloud generation based on disparity a while ago, and decided to stick with this option. I believe there were some performance differences, but I don't exactly recall. Feel free to try the both, I'm sure we'd love to hear a conclusive investigation on their differences in terms of CPU load & accuracy

**Comment by PonyZhou** [comment]
Thanks for reply! And i did not make the code of PX4/disparity_to_point_cloud, but when i launched local_planner_realsense.launch,  the same waring "Planner abort: missing required data " occurred. So I guess local_planner node cannot use /depth/points from realsense by default.

**Comment by PonyZhou** [comment]
How can local_planner node use /depth/points from realsense directly without disparity_to_point_cloud?

**Comment by nicovanduijn** [comment]
It was a long time ago I tried this, and things can change quickly, you will have to do some digging on your own there. I vaguely recall that I started here: https://github.com/PX4/avoidance/blob/c0c159bb6d260e323a9140c8f277daf6db2bdecb/local_planner/launch/rs_depthcloud.launch#L31
and then you have to adjust the the transform trees correctly, which I don't recall the details of. There may be more idiosyncrasies of the realsense that make your life miserable when trying to do this, such as bandwidth limitations on USB2.0 (some streams missing, aka. you can't have a pointcloud and RGB image concurrently or things like that).

This is not a support forum, so please refrain from opening issues just to ask for help. There's the forum and slack channels for this.

**Comment by PonyZhou** [comment]
Thanks for your instruction and suggestion.
