### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Sunchanghao** [PX4/avoidance#545]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
YAML_CPP_INCLUDE_DIR
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/global_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner
   used as include directory in directory /home/sch/catkin_ws/src/avoidance/local_planner

**Comment by Jaeyoung-Lim** [comment]
@Sunchanghao Can you check if yaml_cpp is insalled? try
`sudo apt install ros-kinetic-yaml-*`
if you are running ros kinetic

**Comment by Sunchanghao** [comment]
@Jaeyoung-Lim Thx I have installed this:ros-kinetic-yaml-cpp-0-3
when my fist time to install this node,it has no questiion
after I use another computer download this node and build it,cmake error

**Comment by mrivi** [comment]
plaese make sure you have run `sudo apt install ros-kinetic-yaml-*` on all your machines.
