### ISSUE TITLE
where is safety margin variable?

### ISSUE THREAD

**Issue by maerad7** [PX4/avoidance#546]
We are currently testing drones with a drone size of about 60cm. If you test with a larger drone here, you'll hit an obstacle. So we want to control the safety margin. I'm asking because I didn't find a safety margin in the code. **Where is the safety margin?** 

I want to change to drone size 1.2m.

**Comment by nicovanduijn** [comment]
[This] (https://github.com/PX4/avoidance/blob/af5b0351317cd680b11696399d2ca32f42e70a5a/local_planner/cfg/LocalPlannerNode.cfg#L15) parameter is closest to what you're looking for I think. But note that it does not guarantee that minimum distance at all times

**Comment by maerad7** [comment]
Does it mean 8.5, 0.0, 30?
Thank you for your prayer.

**Comment by nicovanduijn** [comment]
It's a parameter you can change dynamically through RQT reconfigure, I suggest doing so rather than changing that line. The 8.5/0/30 are default/min/max respectively
