### ISSUE TITLE
Regarding safety_area configuration in px4_config.yaml

### ISSUE THREAD

**Issue by darshanz** [PX4/avoidance#551]
In px4_config.yaml, there is a parameter called safety_area.
# safety_area
safety_area:
  p1: {x:  1.0, y:  1.0, z:  1.0}
  p2: {x: -1.0, y: -1.0, z: -1.0} 

I was wondering if it has anything to do with the distance between the drone and obstacle. Is it related to the minimum distance from the obstacle?
Some insights into the meaning of that parameter would be appreciated.
Thanks.

**Comment by mrivi** [comment]
No, it's releted to the safety area plugin in mavros. However the corresponding mavlink message SAFETY_ALLOWED_AREA isn't supported in px4. So that field in the configuration file isn't doing anything

**Comment by darshanz** [comment]
Thank you.
