### ISSUE TITLE
Ideas about "maintaining height relative to ground" & "judgement the state of destination position"

### ISSUE THREAD

**Issue by JoeyLeeNPU** [PX4/avoidance#558]
We have tested local planner on my drone in the indoor navigation mission in these months.
**1. Maintaining height relative to ground**
We use two methods to obtain altitude for the drone, one is down-pointing lidar (relative height to ground) , the other is SLAM (absolute height to local frame origin). But, maintaining a constant height relative to ground is a difficult problem with a down-pointing lidar. So, how should I do in order to keep a constant height relative to ground when using SLAM altitude?

**2. Judgement the state of destination position**
We need to evaluate the relative position of the destination and surrounding obstacles. If the destination is too close to the obstacles, we should give a signal that the mission is completed instead of flying.

Thanks,
Joey

**Comment by mrivi** [comment]
1. dev team is focused on outdoor scenarios and we use GPS as position source 
2. we have chosen a different approach. if a waypoint isn't reachable the vehicle will go to next waypoint avaible.
