### ISSUE TITLE
where is safety margin variable in local_planner?

### ISSUE THREAD

**Issue by Norton-z** [PX4/avoidance#570]
i want to know the value of safety margin in local_planner?
where is the safety margin variable defined?
and where is the cost parameters in the cost function for local_planner?
@mrivi @baumanta

**Comment by jkflying** [comment]
It gets the value from the firmware for CP_DIST

**Comment by Norton-z** [comment]
what is CP_DIST? can i find the parameters in the node?

**Comment by baumanta** [comment]
CP_DIST is for collision prevention only (position flight mode) as far as I can remember. If you want to keep a certain distance during a mission, you would need to tweek this one here: https://github.com/PX4/avoidance/blob/c0c159bb6d260e323a9140c8f277daf6db2bdecb/local_planner/cfg/LocalPlannerNode.cfg#L15
But be careful it is one on many cost terms, so some value sets might not produce good results.

For the future, this is not a support forum. Please ask questions on the forum of slack
