### ISSUE TITLE
How to obtain pointcloud message in the code?

### ISSUE THREAD

**Issue by Norton-z** [PX4/avoidance#573]
Where does the point cloud information come from in the local planner simulation? directly from depth camera or stereo camera? without any filtering?

**Comment by baumanta** [comment]
this is a question and not an issue, please ask on the forum or slack

**Comment by Norton-z** [comment]
I want to know which node/file in local planner of the project is used to obtain pointcloud from camera? I can't find it. Thanks a lot!
