### ISSUE TITLE
Feed the local planner's output into bezier curve trajectory msgs

### ISSUE THREAD

**Issue by JoeyLeeNPU** [PX4/avoidance#574]
Hi, 
I found that PX4 1.11 would integrate a new trajectory msgs about bezier curve for avoidance. 
Maybe the trajectory generated by the bezier curve is smoother than the discrete waypoints. 

Anyone want to have a test about this on local planner (offboard mode is better)? 
Joey

**Comment by mrivi** [comment]
At the moment there isn't any plan to support Bezier trajectories for the local planner. If this is something that interests you, you can try to modify the planner. You can use mission mode directly, no need to use offboard. You only need to specify the correct type in the mavros_msgs::Trajectory
