### ISSUE TITLE
[Local Planner] Can't see buildings in rviz when launched with test_city_2.world

### ISSUE THREAD

**Issue by ytw1996** [PX4/avoidance#582]
**Describe the bug**
After I modified the local_planner_stereo.launch file with the replacement of 

> simple_obstacle

 in line 3 with 

> test_city_2

, I run `roslaunch local_planner local_planner_stereo.launch` in a terminal and can't see buildings in the rviz. I can see the drone model with some red feature points it detects as shown in the figure
![Screenshot from 2020-05-22 10-30-16](https://user-images.githubusercontent.com/26813384/82625331-6d4a7b00-9c17-11ea-9350-d7cf395147b9.png)
However, I can launch the default local_planner_stereo.launch file without trouble and the drone can be armed and navigate to points I set.
I am attaching the output in a file.
**Expected behavior**
In the rviz, the buildings are displayed.
**Log Files** 
[terminal.log](https://github.com/PX4/avoidance/files/4665803/terminal.log)

**Comment by nicovanduijn** [comment]
the visualization in RViz is not automatically tied to Gazebo. It's a pretty hacky implementation that loads a (manually created) yaml file that places the objects accordingly...

**Comment by nicovanduijn** [comment]
Basically, you need to create `test_city_2.yaml` by hand if you want this to work

**Comment by ytw1996** [comment]
@nicovanduijn Thanks for your replying

**Comment by pkyadav73199** [comment]
@nicovanduijn  is there any other way to launch test_city_2.world file in rviz without the use of ymal file ??

**Comment by baumanta** [comment]
@pkyadav73199 No. Not if you want the world to show in rviz.
