### ISSUE TITLE
FCU  avoidance system connecting and time out over and over

### ISSUE THREAD

**Issue by AldoCF96** [PX4/avoidance#584]
these are the outputs of running:
`roslaunch local_planner avoidance.launch fcu_url:=/dev/ttyACM0:115200`
`rostopic hz /local_pointcloud`

![image](https://user-images.githubusercontent.com/50414883/82981497-2d3e1c00-9fba-11ea-9f24-996dc8944d05.png)

the avoidance system is connecting and disconnecting, I am not sure what is the error ?

**Comment by baumanta** [comment]
Your pointcloud rate is way too low. We recommend using something around 10-15Hz. The planner complains (timeout) because it does not get the data at the right frequency

**Comment by AldoCF96** [comment]
I havent changed the pointcloud rate. I just took the files as they were, where do I change the pointcloud rate ?

**Comment by AldoCF96** [comment]
I tried changing the fps but it did not help

**Comment by baumanta** [comment]
most likely it is a hardware limitation of your laptop. The code as prided works, you should not need to change anything (e.g. frame rates) for SITL. Try running it on a more powerful computer, maybe a desktop.

**Comment by AldoCF96** [comment]
Yeah, I will try that, as of now I am running in actual hardware.  so I am not using SITL right now,  any recommended hardware ?

**Comment by baumanta** [comment]
So we successfully had it running on: Nvidia jetson TX2/TX1, Nvidia IMX8, Intel Up Core, Intel NUC
With any of these or comparable boards you would be on the safe side

**Comment by baumanta** [comment]
Closing as this is no code issue

**Comment by AldoCF96** [comment]
what is the intel UP core rate?? I was working with a board of similar specs and got around 9.6 hz is it good ?

**Comment by baumanta** [comment]
That should do. And you will for sure not see the timeout anymore
