### ISSUE TITLE
Get point cloud in a .csv file

### ISSUE THREAD

**Issue by Cristian-wp** [PX4/avoidance#585]
Hello,
for simulation purpose I need to save the data get from the simulated camera in the local_planner_depth-camera simulation.
Can somebody help me? Normally for debug purpose I use the > linux command to write the stream of data, but this time is different...
Do I have to write a new ROS node in order to do this or there is a more simple way?
Thanks in advance!

**Comment by baumanta** [comment]
this is not an issue. Please use the forum (https://discuss.px4.io/) or slack for PX4 or avoidance related questions. Your question would be rather suitable for a ROS forum though, as you want to safe a ROS topic as a .csv file.
