### ISSUE TITLE
What is the purpose of the local_planner_manager? There is a flow chart of the avoidance feature?

### ISSUE THREAD

**Issue by Cristian-wp** [PX4/avoidance#586]
Good morning,
I am trying to understand better the code of the PX4 avoidance and I can not understand the purpose of this duplication of node.
As you can see from the rqt_graph there is a duplication of the local_planner_nodelet with a different name. 

![rosgraph](https://user-images.githubusercontent.com/61200634/83233840-9f1b8e80-a18f-11ea-9292-858d396a0259.png)

The read ad subscribe the bond, I have already see the content of this message but I can not understand the purpose.
Can someone explain me better this thing? Maybe there is a flow chart of this feature that can help me to understand better the logic?
I have already read the eth thesis and there are easy to understand, but I need a help with the code.

**Comment by baumanta** [comment]
The local planner is designed as a nodelet (not a node). This means it has a manager. You can read up the principle by researching ROS nodelets. In our case this is more efficient when running on hardware as the structure core nodelet can register under the same manager (so it belongs to the same process) and we therefore do not have to pass the large pointcloud message between different processes.
