### ISSUE TITLE
Global Planner, Safe Landing Planner and GPS

### ISSUE THREAD

**Issue by Cristian-wp** [PX4/avoidance#591]
Hello, 
is possible to run the global planner without using a GPS? I need to fly my drone inside a building so I can not relie on position data from GPS.

For what concern the landing planner, is possible to turn off the local/global planner during the fly and start the landing one?

Thanks in advance  :-)

**Comment by jkflying** [comment]
You need some sort of positioning (eg. VIO), but it doesn't need to be GPS.

As far as the landing planner and switching, currently this isn't supported. If you get it working, please consider contributing!

Hope this helps.
