### ISSUE TITLE
Obstacle Avoidance for Drones Using a 3DVFH* Algorithm

### ISSUE THREAD

**Issue by zhanqx1024** [PX4/avoidance#593]
I see the local planner avoidance is based on the 3DVFH+,but It's explaintion is too simple , I find you have reference the paper 3DVFH*, where can I get the paper of Obstacle Avoidance for Drones Using a 3DVFH* Algorithm, I can not find it in the  EI and Reaserchgate .Thank you very much

**Comment by nicovanduijn** [comment]
It's not on researchgate. This is the only paper on it: https://drive.google.com/file/d/1yjDtxRrIntr5Mdaj9CCB4IFJn0Iy2-bR/view

**Comment by ho4ngt** [comment]
> It's not on researchgate. This is the only paper on it: https://drive.google.com/file/d/1yjDtxRrIntr5Mdaj9CCB4IFJn0Iy2-bR/view

Can you please share this paper again? That link is no longer working. Thank you!

**Comment by nicovanduijn** [comment]
It's been updated on the readme a while ago with #690

**Comment by ho4ngt** [comment]
> It's been updated on the readme a while ago with #690

Thank you!
