### ISSUE TITLE
docker-compose installation instructions should be updated

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/avoidance#87]
According to the [readme](https://github.com/PX4/avoidance/tree/master/docker/demo) in the docker folder, the docker-compose installation is instructed to be done as
```
apt install docker-compose
```

However, the docker-compose installed using apt is `1.8.1` which is outdated. 
This produces an error as the `docker-compose.yaml` uses `version: '3'` which is [not compatible](https://docs.docker.com/compose/compose-file/compose-versioning/) with `1.8.1`

A better approach is to install the docker-compose using the instructions provided [here](https://docs.docker.com/compose/install/)

**Comment by JonasVautherin** [comment]
That's what I was doing [here](https://github.com/PX4/avoidance/blob/master/docker/run.py#L70), actually. Would be worth updating the docker-compose version there as well.

**Comment by shairubin** [comment]
when trying to run the run.py I get

File "run.py", line 117, in <module>
    main(args)
  File "run.py", line 10, in main
    runGlobalPrerequisites()
  File "run.py", line 54, in runGlobalPrerequisites
    while isDockerComposeNotInstalled():
  File "run.py", line 58, in isDockerComposeNotInstalled
    return shutil.which("docker-compose") == ''
AttributeError: 'module' object has no attribute 'which'

**Comment by JonasVautherin** [comment]
@shairubin: Are you running `run.py` with python3?

**Comment by shairubin** [comment]
No — will try 


Sent from Yahoo Mail for iPhone


On Thursday, July 5, 2018, 12:20 PM, Jonas Vautherin <notifications@github.com> wrote:


@shairubin: Are you running run.py with python3?
