### ISSUE TITLE
Link to instructions to run on odroid is broken

### ISSUE THREAD

**Issue by mzahana** [PX4/avoidance#91]
Hi.

The link that points to running the package on odroid is broken.
https://github.com/PX4/avoidance#running-on-odroid

Could you please update it?

Thanks.

**Comment by adipandas** [comment]
Updated link: [Running on Odroid](https://github.com/PX4/avoidance/tree/master/global_planner/resource/odroid)

**Comment by mzahana** [comment]
Thanks. Which planner is tested to work outdoor? I see the README under the global planner.
Also, I have an Intel Up board with Realsense R200. Would the setup on the Up board be similar?
Thanks again.

**Comment by mrivi** [comment]
@mzahana Global planner was tested outdoor, running on odroid.
However, right now most of our efforts are on the local planner. We are running it on Intel Aero (https://docs.px4.io/en/flight_controller/intel_aero.html)

**Comment by mzahana** [comment]
Can the same setup on odroid be used to run local planer?

**Comment by mzahana** [comment]
**Notes**:
* There is NO `odroid` branch in [PX4/avoidance](https://github.com/PX4/avoidance)
* There is NO `half_resolution` branch in [PX4/uvc_ros_driver](https://github.com/PX4/uvc_ros_driver)
