### ISSUE TITLE
Memory issues: check dynamic data structures

### ISSUE THREAD

**Issue by bkueng** [PX4/avoidance#96]
While looking through the code I came accross https://github.com/PX4/avoidance/blob/master/local_planner/src/nodes/local_planner.cpp#L208 and https://github.com/PX4/avoidance/blob/master/local_planner/src/nodes/local_planner_node.cpp#L894.
Both instances increase an `std::vector` at each iteration but the size is not bounded, and nowhere elements are removed. This means the process will run out of memory when running long enough (it will take a long time though).

I suggest to check all dynamic data structures used in the entire project, as these 2 instances were the only ones that I checked.

**Comment by baumanta** [comment]
I think that issue was related to the time vectors that stored the computation time for some functions for debugging. I deleted all of them, so that should not be relevant anymore
