### ISSUE TITLE
Check usage of std::clock()

### ISSUE THREAD

**Issue by bkueng** [PX4/avoidance#97]
[std::clock](https://en.cppreference.com/w/cpp/chrono/c/clock) measures the processor time and is in many cases not what you want.

For example it's used to calculate `dt` in https://github.com/PX4/avoidance/blob/master/local_planner/src/nodes/waypoint_generator.cpp#L243.
This is not correct and [std::chrono::high_resolution_clock::now](https://en.cppreference.com/w/cpp/chrono/high_resolution_clock/now) should be used instead.

`std::clock` is used at several places and all of them need to be validated.

**Comment by baumanta** [comment]
Right, thanks for looking into it! I agree, this is wrong. I used ros::Time:now() in some cases. For constistency, I think we should choose either that or chrono. Which on do you like better?

http://wiki.ros.org/roscpp/Overview/Time

**Comment by baumanta** [comment]
Thanks! I think I''ll go with ros::Time::now(). Just to keep all options open for simulation

**Comment by nicovanduijn** [comment]
Has been taken care of as part of #102 (7be4b85)
